# regula-ignore
"""Tests for AI-generated code governance scanner."""

import os
import sys
import tempfile
from pathlib import Path

import pytest

sys.path.insert(0, str(Path(__file__).resolve().parent.parent / "scripts"))

from ai_code_governance import (
    EXPLICIT_MARKERS,
    _assess_governance,
    _detect_tool_configs,
    _parse_git_output,
    _scan_file_for_markers,
    format_ai_codegen_text,
    scan_ai_generated_code,
)


# ---------------------------------------------------------------------------
# Marker detection — one test per generator
# ---------------------------------------------------------------------------

class TestExplicitMarkers:
    def test_detect_github_copilot(self):
        content = "# Generated by GitHub Copilot\nx = 1"
        findings = _scan_file_for_markers(content, "app.py")
        assert len(findings) == 1, f"expected exactly 1 finding, got {len(findings)}"
        assert findings[0]["generator"] == "GitHub Copilot"
        assert findings[0]["provider"] == "Microsoft/GitHub"
        assert findings[0]["confidence"] == "high"
        assert findings[0]["line"] == 1

    def test_detect_claude(self):
        content = "// Generated with Claude\nconst x = 1;"
        findings = _scan_file_for_markers(content, "app.js")
        assert len(findings) == 1, f"expected exactly 1 finding, got {len(findings)}"
        assert findings[0]["generator"] == "Claude"
        assert findings[0]["provider"] == "Anthropic"

    def test_detect_claude_co_authored(self):
        content = "# Co-Authored-By: Claude (Anthropic)\ndef f(): pass"
        findings = _scan_file_for_markers(content, "main.py")
        assert len(findings) == 1, f"expected exactly 1 finding, got {len(findings)}"
        assert findings[0]["generator"] == "Claude"

    def test_detect_chatgpt(self):
        content = "# Generated by ChatGPT\nimport os"
        findings = _scan_file_for_markers(content, "util.py")
        assert len(findings) == 1, f"expected exactly 1 finding, got {len(findings)}"
        assert findings[0]["generator"] == "ChatGPT"
        assert findings[0]["provider"] == "OpenAI"

    def test_detect_chatgpt_gpt4(self):
        content = "// Generated using GPT-4\nlet x = 1;"
        findings = _scan_file_for_markers(content, "app.ts")
        assert len(findings) == 1, f"expected exactly 1 finding, got {len(findings)}"
        assert findings[0]["generator"] == "ChatGPT"

    def test_detect_cursor(self):
        content = "# Generated by Cursor\nx = 1"
        findings = _scan_file_for_markers(content, "app.py")
        assert len(findings) == 1, f"expected exactly 1 finding, got {len(findings)}"
        assert findings[0]["generator"] == "Cursor"
        assert findings[0]["provider"] == "Anysphere"

    def test_detect_codewhisperer(self):
        content = "# Generated by Amazon Q\nimport json"
        findings = _scan_file_for_markers(content, "handler.py")
        assert len(findings) == 1, f"expected exactly 1 finding, got {len(findings)}"
        assert findings[0]["generator"] == "Amazon Q Developer"
        assert findings[0]["provider"] == "AWS"

    def test_detect_gemini(self):
        content = "// Generated by Gemini\npackage main"
        findings = _scan_file_for_markers(content, "main.go")
        assert len(findings) == 1, f"expected exactly 1 finding, got {len(findings)}"
        assert findings[0]["generator"] == "Gemini Code Assist"
        assert findings[0]["provider"] == "Google"

    def test_no_markers_in_clean_file(self):
        content = "def hello():\n    print('world')\n"
        findings = _scan_file_for_markers(content, "clean.py")
        assert len(findings) == 0

    def test_marker_line_number(self):
        content = "import os\nimport sys\n# Generated by GitHub Copilot\nx = 1"
        findings = _scan_file_for_markers(content, "app.py")
        assert findings[0]["line"] == 3


# ---------------------------------------------------------------------------
# Tool config detection
# ---------------------------------------------------------------------------

class TestToolConfigs:
    def test_detect_cursorrules(self):
        with tempfile.TemporaryDirectory() as td:
            Path(td, ".cursorrules").write_text("rules here")
            configs = _detect_tool_configs(td)
            assert len(configs) == 1, f"expected 1 config, got {len(configs)}"
            assert configs[0]["tool"] == "Cursor"

    def test_detect_claude_md(self):
        with tempfile.TemporaryDirectory() as td:
            Path(td, "CLAUDE.md").write_text("# Instructions")
            configs = _detect_tool_configs(td)
            tools = [c["tool"] for c in configs]
            assert "Claude Code" in tools

    def test_detect_aider_config(self):
        with tempfile.TemporaryDirectory() as td:
            Path(td, ".aider.conf.yml").write_text("model: gpt-4")
            configs = _detect_tool_configs(td)
            assert configs[0]["tool"] == "Aider"

    def test_detect_amazonq_dir(self):
        with tempfile.TemporaryDirectory() as td:
            Path(td, ".amazonq").mkdir()
            configs = _detect_tool_configs(td)
            assert configs[0]["tool"] == "Amazon Q Developer"

    def test_no_configs_in_empty_dir(self):
        with tempfile.TemporaryDirectory() as td:
            configs = _detect_tool_configs(td)
            assert len(configs) == 0


# ---------------------------------------------------------------------------
# Git commit signal detection
# ---------------------------------------------------------------------------

class TestGitSignals:
    def test_co_authored_claude(self):
        git_output = "abc123abc123abc123abc123abc123abc123abcd fix: thing\nCo-Authored-By: Claude (Anthropic)\n"
        signals = _parse_git_output(git_output)
        assert len(signals) == 1, f"expected 1 signal, got {len(signals)}"
        assert signals[0]["generator"] == "Claude"

    def test_bracket_tag_copilot(self):
        git_output = "def456def456def456def456def456def456defc [copilot] add function\n"
        signals = _parse_git_output(git_output)
        assert len(signals) == 1, f"expected 1 signal, got {len(signals)}"
        assert signals[0]["generator"] == "GitHub Copilot"

    def test_ai_generated_tag(self):
        git_output = "aaa111aaa111aaa111aaa111aaa111aaa111aaab [AI-generated] new module\n"
        signals = _parse_git_output(git_output)
        assert len(signals) == 1, f"expected 1 signal, got {len(signals)}"
        assert signals[0]["generator"] == "Unknown AI"

    def test_no_signals_in_normal_commits(self):
        git_output = "bbb222bbb222bbb222bbb222bbb222bbb222bbbc fix: normal commit message\n"
        signals = _parse_git_output(git_output)
        assert len(signals) == 0


# ---------------------------------------------------------------------------
# Governance assessment
# ---------------------------------------------------------------------------

class TestGovernance:
    def test_empty_project_score_zero(self):
        with tempfile.TemporaryDirectory() as td:
            gov = _assess_governance(td)
            assert gov["score"] == 0
            assert gov["has_ai_policy"] is False
            assert gov["has_disclosure"] is False
            assert gov["has_model_card"] is False
            assert gov["has_tool_inventory"] is False

    def test_policy_only_score_40(self):
        with tempfile.TemporaryDirectory() as td:
            Path(td, "ai-policy.md").write_text("# AI Policy")
            gov = _assess_governance(td)
            assert gov["score"] == 40
            assert gov["has_ai_policy"] is True

    def test_full_governance_score_100(self):
        with tempfile.TemporaryDirectory() as td:
            Path(td, "ai-policy.md").write_text("# AI Policy")
            Path(td, "AI_DISCLOSURE.md").write_text("# Disclosure")
            Path(td, "MODEL_CARD.md").write_text("# Model Card")
            Path(td, "AI_TOOLS.md").write_text("# Tools")
            gov = _assess_governance(td)
            assert gov["score"] == 100

    def test_docs_subdir_policy(self):
        with tempfile.TemporaryDirectory() as td:
            docs = Path(td, "docs")
            docs.mkdir()
            (docs / "AI_GOVERNANCE.md").write_text("# Gov")
            gov = _assess_governance(td)
            assert gov["has_ai_policy"] is True


# ---------------------------------------------------------------------------
# Full scan integration
# ---------------------------------------------------------------------------

class TestFullScan:
    def test_empty_project(self):
        with tempfile.TemporaryDirectory() as td:
            result = scan_ai_generated_code(td, include_git=False)
            assert result["markers_found"] == []
            assert result["tool_configs"] == []
            assert result["git_signals"] == []
            assert result["summary"]["generators_detected"] == []
            assert result["summary"]["files_with_markers"] == 0
            assert result["summary"]["transparency_compliant"] is False
            assert "limitations" in result
            assert "explicit markers only" in result["limitations"]

    def test_project_with_markers(self):
        with tempfile.TemporaryDirectory() as td:
            Path(td, "app.py").write_text("# Generated by GitHub Copilot\nx = 1\n")
            Path(td, "clean.py").write_text("def f(): pass\n")
            result = scan_ai_generated_code(td, include_git=False)
            assert result["summary"]["files_with_markers"] == 1
            assert result["summary"]["total_files_scanned"] == 2
            assert "GitHub Copilot" in result["summary"]["generators_detected"]

    def test_project_with_config_and_markers(self):
        with tempfile.TemporaryDirectory() as td:
            Path(td, ".cursorrules").write_text("rules")
            Path(td, "main.py").write_text("# Generated with Claude\npass\n")
            result = scan_ai_generated_code(td, include_git=False)
            gens = result["summary"]["generators_detected"]
            assert "Claude" in gens
            assert "Cursor" in gens

    def test_fully_governed_project(self):
        with tempfile.TemporaryDirectory() as td:
            Path(td, "ai-policy.md").write_text("# Policy")
            Path(td, "AI_DISCLOSURE.md").write_text("# Disclosure")
            Path(td, "MODEL_CARD.md").write_text("# Card")
            Path(td, "AI_TOOLS.md").write_text("# Tools")
            result = scan_ai_generated_code(td, include_git=False)
            assert result["summary"]["governance_score"] == 100
            assert result["summary"]["transparency_compliant"] is True

    def test_limitations_always_present(self):
        with tempfile.TemporaryDirectory() as td:
            result = scan_ai_generated_code(td, include_git=False)
            assert "limitations" in result
            assert len(result["limitations"]) > 0


# ---------------------------------------------------------------------------
# Text formatting
# ---------------------------------------------------------------------------

class TestTextFormat:
    def test_format_empty_project(self):
        with tempfile.TemporaryDirectory() as td:
            result = scan_ai_generated_code(td, include_git=False)
            text = format_ai_codegen_text(result)
            assert "AI-Generated Code Governance Report" in text
            assert "No AI code generators detected" in text
            assert "Limitations" in text

    def test_format_with_findings(self):
        with tempfile.TemporaryDirectory() as td:
            Path(td, "app.py").write_text("# Generated by GitHub Copilot\nx = 1\n")
            result = scan_ai_generated_code(td, include_git=False)
            text = format_ai_codegen_text(result)
            assert "GitHub Copilot" in text
            assert "Governance Score:" in text
            assert "Art 50/52" in text

    def test_format_governance_good(self):
        with tempfile.TemporaryDirectory() as td:
            Path(td, "ai-policy.md").write_text("# Policy")
            Path(td, "AI_DISCLOSURE.md").write_text("# D")
            Path(td, "MODEL_CARD.md").write_text("# M")
            Path(td, "AI_TOOLS.md").write_text("# T")
            result = scan_ai_generated_code(td, include_git=False)
            text = format_ai_codegen_text(result)
            assert "100/100 (GOOD)" in text
            assert "COMPLIANT" in text

    def test_format_recommendations(self):
        with tempfile.TemporaryDirectory() as td:
            result = scan_ai_generated_code(td, include_git=False)
            text = format_ai_codegen_text(result)
            assert "Recommendations" in text
            assert "AI_USAGE_POLICY.md" in text
