# regula-ignore
"""F32: the auditor blanked the citation form it tells you to use.

`strip_noise()` removes inline code spans as noise, with one exception:
a span that is *entirely* a repo-file path which resolves on disk is
kept, because backticks are this repo's idiomatic way of citing a source
file.

The exception used `FILE_REF_RE.fullmatch`, so it accepted

    `benchmarks/label.py`

and rejected

    `benchmarks/label.py score --breakdown`

MEASURED 2026-07-29 on docs/TRUST.md L226. The line
`**Development corpus per-tier precision (v1.7.3, ...):**` names the exact
command that produces the table beneath it. `FILE_REF_RE` matches
`benchmarks/label.py` on the raw line and matches NOTHING after
`strip_noise`, so `paragraph_has_source()` reported `no-source` for a
paragraph whose entire content is a provenance statement.

**Why that is backwards.** PROGRAMME.md Principle 1 lists the accepted
evidence tags, and one of them is **MEASURED (command + output)**. The
auditor's own failure message tells the reader to add "a reference to an
existing file". Citing the file worked; citing the command that produced
the number did not. The gate was blanking the remedy it recommends.

The repair widens the exception: preserve the span when ANY token inside
it resolves to a real file under REPO_ROOT. It still cannot be satisfied
by prose, because a real file has to exist for the span to survive.

Repo-wide effect of the change alone, one variable, measured over all
tracked Markdown and HTML: findings 360 -> 355, total claims unchanged at
1329. It resolved five real findings and hid no claims.

This file is the regression pair the repair owes: a correctly-sourced
claim must pass, and a genuinely unsourced one must still fail.
"""
from __future__ import annotations

import sys
from pathlib import Path

import pytest

REPO_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO_ROOT / "scripts"))

import claim_auditor as ca  # noqa: E402


def _sourced(markdown: str) -> tuple[bool, str]:
    """Run the real pipeline: strip_noise then paragraph_has_source."""
    cleaned = ca.strip_noise(markdown, ".md")
    paragraphs = ca.split_paragraphs(cleaned)
    assert paragraphs, "fixture produced no paragraphs"
    return ca.paragraph_has_source(paragraphs[0][2], None)


# --- the PASS half: correctly-sourced claims must be recognised ----------

def test_command_citation_naming_a_real_file_is_a_source() -> None:
    """The exact construction that failed on docs/TRUST.md L226."""
    para = ("Development corpus per-tier precision was 75.0% "
            "(v1.7.3, `benchmarks/label.py score --breakdown`).")
    ok, reason = _sourced(para)
    assert ok, f"command citation not accepted as a source (reason={reason})"
    assert reason.startswith("file-ref:"), reason


def test_bare_file_citation_still_works() -> None:
    """The pre-existing behaviour must not regress."""
    para = "Overall precision is 83.5% (`benchmarks/README.md`)."
    ok, reason = _sourced(para)
    assert ok, f"bare file citation regressed (reason={reason})"
    assert reason.startswith("file-ref:"), reason


def test_interpreter_prefixed_command_is_a_source() -> None:
    """`python3 scripts/foo.py --flag` is how this repo quotes commands."""
    para = ("The canonical count is regenerated by "
            "`python3 scripts/site_facts.py` and is 2,430.")
    ok, reason = _sourced(para)
    assert ok, f"interpreter-prefixed command rejected (reason={reason})"
    assert reason.startswith("file-ref:"), reason


def test_known_boundary_a_command_naming_only_a_directory_is_not_a_source() -> None:
    """Documented limitation, asserted so it cannot drift silently.

    `FILE_REF_RE` requires a file extension, so a command whose only path
    token is a directory (`pytest tests/ --collect-only`) does not source
    its paragraph. This was found by this test failing on its first run:
    the expectation was wrong, not the code. Widening the rule to bare
    directories would make any mention of `tests/` a citation, which is
    materially easier to satisfy by accident than naming a real file.

    If this boundary is ever revisited, change it deliberately and
    re-measure the repo-wide finding count in the same commit.
    """
    para = ("The suite collects 2,430 tests "
            "(`python3 -m pytest tests/ --collect-only -q`).")
    ok, reason = _sourced(para)
    assert not ok, "a directory-only command was accepted as a source"
    assert reason == "no-source", reason


# --- the FAIL half: unsourced claims must still fail ---------------------

def test_bare_number_with_no_reference_still_fails() -> None:
    """The control. If this passes, the repair has broken the gate."""
    para = "Overall precision is 83.5% and high-risk precision is 33%."
    ok, reason = _sourced(para)
    assert not ok, "an unsourced numeric claim was accepted as sourced"
    assert reason == "no-source", reason


def test_existence_check_discriminates_real_from_invented_paths() -> None:
    """Anti-gaming: the span survives ONLY if its path resolves on disk.

    **This test asserts a CONTRAST, deliberately, and the earlier version
    of it was defective.** It used to assert only the negative half: that
    a command naming a nonexistent file is not a source. That passes with
    the F32 repair reverted, because before the repair EVERY non-fullmatch
    span was blanked, so the nonexistent path was rejected for a
    completely different reason. It therefore asserted current behaviour
    rather than correct behaviour, and could not distinguish "the
    existence check works" from "the repair is not installed".

    Found 29 July 2026 by reverting the repair in a scratch worktree and
    reading which tests still passed. Measurement rule 4: an absent signal
    is not a passing signal.

    Asserting both halves in one test fixes it. The positive half fails
    when the repair is reverted, so the test as a whole is fail-before,
    pass-after, while the negative half still guards the existence check
    against being dropped later.
    """
    real = "benchmarks/label.py"
    ghost = "benchmarks/does_not_exist_ab12cd34.py"
    assert (REPO_ROOT / real).exists(), "fixture path should exist"
    assert not (REPO_ROOT / ghost).exists(), "fixture path unexpectedly exists"

    # Identical construction, identical shape, one difference: the file.
    ok_real, reason_real = _sourced(f"Precision is 99.9% (`{real} score --breakdown`).")
    ok_ghost, reason_ghost = _sourced(f"Precision is 99.9% (`{ghost} score --breakdown`).")

    assert ok_real, (
        "a command naming a REAL repo file was not accepted as a source "
        f"(reason={reason_real}); the F32 repair is missing or broken"
    )
    assert not ok_ghost, (
        "a command naming a NONEXISTENT file was accepted as a source "
        f"(reason={reason_ghost}); the existence check has been dropped"
    )
    assert reason_ghost == "no-source", reason_ghost


def test_prose_inside_backticks_is_not_a_source() -> None:
    """Backticked prose with no file token must remain noise."""
    para = "Precision is 83.5% (`we measured this carefully, honest`)."
    ok, reason = _sourced(para)
    assert not ok, "backticked prose was accepted as a source"
    assert reason == "no-source", reason


# --- the two files this repair was diagnosed on -------------------------

@pytest.mark.parametrize("doc", ["docs/TRUST.md", "docs/MODEL_CARD.md"])
def test_named_documents_are_clean(doc: str) -> None:
    """docs/TRUST.md and docs/MODEL_CARD.md must stay at zero unsourced.

    These two were the whole reason `--diff-base` was red on this branch:
    the CI claim gate scans whole files, so ANY commit touching either one
    inherited every unsourced claim already in it, including every count
    cascade. Keeping them at zero is what keeps the gate usable.
    """
    report = ca.scan_file(REPO_ROOT / doc, ca.load_allowlist())
    assert report.scanned, f"{doc} was not scanned"
    detail = "\n".join(
        f"  L{f.claim.line} [{f.claim.kind}] {f.claim.snippet!r}"
        for f in report.findings
    )
    assert not report.findings, f"{doc} has {len(report.findings)} unsourced:\n{detail}"
