# regula-ignore
"""
AI-Generated Code Governance Scanner for Regula.

Detects EXPLICIT markers of AI-generated code in a project and assesses
governance documentation quality. This scanner looks for comments, metadata,
tool configurations, and git commit signals that indicate AI tool usage.

IMPORTANT LIMITATION: This scanner detects explicit markers only (comments,
config files, commit messages). It does NOT use stylistic heuristics, which
have unacceptable false-positive rates. Absence of markers does NOT mean
code is human-written. For comprehensive provenance tracking, implement a
code provenance policy.

Relevant EU AI Act articles:
- Article 50: Transparency obligations for AI-generated content
- Article 52: Disclosure requirements for AI-generated content

No external dependencies — stdlib only.
"""

import os
import re
import subprocess
import sys
from pathlib import Path
from typing import Optional

_scripts_dir = str(Path(__file__).parent)
if _scripts_dir not in sys.path:
    sys.path.insert(0, _scripts_dir)

from constants import CODE_EXTENSIONS, SKIP_DIRS


# ---------------------------------------------------------------------------
# Explicit generator markers (HIGH confidence)
# ---------------------------------------------------------------------------

EXPLICIT_MARKERS = {
    "github_copilot": {
        "patterns": [
            r"# Generated by GitHub Copilot",
            r"// Generated by GitHub Copilot",
            r"@copilot-generated",
            r"copilot\.generated",
            r"GitHub Copilot.*suggestion",
        ],
        "generator": "GitHub Copilot",
        "provider": "Microsoft/GitHub",
    },
    "claude": {
        "patterns": [
            r"# Generated (?:by|with|using) Claude",
            r"// Generated (?:by|with|using) Claude",
            r"Co-Authored-By:.*Claude",
            r"anthropic.*generated",
            r"@claude-generated",
        ],
        "generator": "Claude",
        "provider": "Anthropic",
    },
    "chatgpt": {
        "patterns": [
            r"# Generated (?:by|with|using) (?:ChatGPT|GPT-4|GPT-3)",
            r"// Generated (?:by|with|using) (?:ChatGPT|GPT-4|GPT-3)",
            r"openai.*generated",
            r"@chatgpt-generated",
        ],
        "generator": "ChatGPT",
        "provider": "OpenAI",
    },
    "cursor": {
        "patterns": [
            r"# Generated (?:by|with|using) Cursor",
            r"// Generated (?:by|with|using) Cursor",
            r"cursor\.ai.*generated",
        ],
        "generator": "Cursor",
        "provider": "Anysphere",
    },
    "codewhisperer": {
        "patterns": [
            r"# Generated (?:by|with|using) (?:CodeWhisperer|Amazon Q)",
            r"// Generated (?:by|with|using) (?:CodeWhisperer|Amazon Q)",
        ],
        "generator": "Amazon Q Developer",
        "provider": "AWS",
    },
    "gemini_code": {
        "patterns": [
            r"# Generated (?:by|with|using) Gemini",
            r"// Generated (?:by|with|using) Gemini",
            r"google.*gemini.*generated",
        ],
        "generator": "Gemini Code Assist",
        "provider": "Google",
    },
}


# ---------------------------------------------------------------------------
# Tool configuration files (HIGH confidence)
# ---------------------------------------------------------------------------

TOOL_CONFIGS = [
    {"path": ".github/copilot-instructions.md", "tool": "GitHub Copilot", "provider": "Microsoft/GitHub"},
    {"path": ".cursorrules", "tool": "Cursor", "provider": "Anysphere"},
    {"path": ".cursor/rules", "tool": "Cursor", "provider": "Anysphere"},
    {"path": "CLAUDE.md", "tool": "Claude Code", "provider": "Anthropic"},
    {"path": ".claudeignore", "tool": "Claude Code", "provider": "Anthropic"},
    {"path": ".aider.conf.yml", "tool": "Aider", "provider": "Aider"},
    {"path": ".coderabbit.yaml", "tool": "CodeRabbit", "provider": "CodeRabbit"},
    {"path": ".continue/config.json", "tool": "Continue.dev", "provider": "Continue"},
    {"path": ".amazonq", "tool": "Amazon Q Developer", "provider": "AWS"},
]


# ---------------------------------------------------------------------------
# Git commit patterns (MEDIUM confidence)
# ---------------------------------------------------------------------------

GIT_COMMIT_PATTERNS = [
    {"pattern": r"Co-Authored-By:.*Claude", "generator": "Claude"},
    {"pattern": r"Co-Authored-By:.*GitHub Copilot", "generator": "GitHub Copilot"},
    {"pattern": r"Co-Authored-By:.*ChatGPT", "generator": "ChatGPT"},
    {"pattern": r"\[AI-generated\]", "generator": "Unknown AI"},
    {"pattern": r"\[copilot\]", "generator": "GitHub Copilot"},
    {"pattern": r"\[claude\]", "generator": "Claude"},
    {"pattern": r"\[chatgpt\]", "generator": "ChatGPT"},
    {"pattern": r"aider:", "generator": "Aider"},
]


# ---------------------------------------------------------------------------
# Governance documentation patterns
# ---------------------------------------------------------------------------

POLICY_FILES = [
    "ai-policy.md", "AI_GOVERNANCE.md", "ai_governance.md",
    "AI_USAGE_POLICY.md", "ai-usage-policy.md",
    "docs/ai-policy.md", "docs/AI_GOVERNANCE.md",
    "docs/ai_governance.md", "docs/AI_USAGE_POLICY.md",
]

DISCLOSURE_FILES = [
    "AI_DISCLOSURE.md", "ai-disclosure.md",
    "docs/AI_DISCLOSURE.md", "docs/ai-disclosure.md",
    "ATTRIBUTION.md", "docs/ATTRIBUTION.md",
]

MODEL_CARD_FILES = [
    "MODEL_CARD.md", "model_card.md", "model-card.md",
    "docs/MODEL_CARD.md", "docs/model_card.md",
]

TOOL_INVENTORY_FILES = [
    "AI_TOOLS.md", "ai-tools.md", "docs/AI_TOOLS.md",
    "docs/ai-tools.md", "AI_INVENTORY.md",
]


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _read_file(filepath: str) -> Optional[str]:
    """Read file content, returning None on failure."""
    try:
        return Path(filepath).read_text(encoding="utf-8", errors="ignore")
    except (PermissionError, OSError):
        return None


def _walk_code_files(project_path: str):
    """Yield (relative_path, absolute_path) for code files."""
    project = Path(project_path).resolve()
    for root, dirs, files in os.walk(project):
        dirs[:] = [d for d in dirs if d not in SKIP_DIRS]
        for filename in files:
            filepath = Path(root) / filename
            if filepath.suffix.lower() in CODE_EXTENSIONS:
                try:
                    rel = str(filepath.relative_to(project))
                except ValueError:
                    rel = str(filepath)
                yield rel, str(filepath)


def _scan_file_for_markers(content: str, rel_path: str):
    """Scan file content for explicit AI generator markers."""
    findings = []
    lines = content.splitlines()
    for marker_id, marker_info in EXPLICIT_MARKERS.items():
        for pattern in marker_info["patterns"]:
            for line_num, line in enumerate(lines, 1):
                if re.search(pattern, line, re.IGNORECASE):
                    findings.append({
                        "file": rel_path,
                        "line": line_num,
                        "generator": marker_info["generator"],
                        "provider": marker_info["provider"],
                        "confidence": "high",
                        "marker_text": line.strip(),
                    })
    return findings


def _detect_tool_configs(project_path: str):
    """Check for AI tool configuration files/directories."""
    project = Path(project_path).resolve()
    found = []
    for cfg in TOOL_CONFIGS:
        target = project / cfg["path"]
        if target.exists():
            found.append({
                "tool": cfg["tool"],
                "config_path": cfg["path"],
                "provider": cfg["provider"],
            })
    return found


def _scan_git_log(project_path: str, max_commits: int = 200):
    """Scan recent git commits for AI-generated code signals."""
    signals = []
    try:
        result = subprocess.run(
            ["git", "log", f"--max-count={max_commits}", "--format=%H %s%n%b"],
            capture_output=True, text=True, timeout=10,
            cwd=project_path,
        )
        if result.returncode != 0:
            return signals
    except (FileNotFoundError, subprocess.TimeoutExpired, OSError):
        return signals

    return _parse_git_output(result.stdout)


def _parse_git_output(git_output: str):
    """Parse git log output for AI signals. Separated for testability."""
    signals = []
    current_hash = None
    for line in git_output.splitlines():
        parts = line.split(" ", 1)
        if len(parts) == 2 and len(parts[0]) == 40 and all(c in "0123456789abcdef" for c in parts[0]):
            current_hash = parts[0][:8]
        for gp in GIT_COMMIT_PATTERNS:
            if re.search(gp["pattern"], line, re.IGNORECASE):
                signals.append({
                    "commit": current_hash or "unknown",
                    "generator": gp["generator"],
                    "message_excerpt": line.strip()[:120],
                })
    return signals


def _assess_governance(project_path: str):
    """Assess governance documentation quality."""
    project = Path(project_path).resolve()

    def _any_exists(file_list):
        return any((project / f).exists() for f in file_list)

    has_policy = _any_exists(POLICY_FILES)
    has_disclosure = _any_exists(DISCLOSURE_FILES)
    has_model_card = _any_exists(MODEL_CARD_FILES)
    has_inventory = _any_exists(TOOL_INVENTORY_FILES)

    score = 0
    if has_policy:
        score += 40
    if has_disclosure:
        score += 30
    if has_model_card:
        score += 15
    if has_inventory:
        score += 15

    return {
        "has_ai_policy": has_policy,
        "has_disclosure": has_disclosure,
        "has_model_card": has_model_card,
        "has_tool_inventory": has_inventory,
        "score": score,
    }


# ---------------------------------------------------------------------------
# Main scanner
# ---------------------------------------------------------------------------

def scan_ai_generated_code(project_path: str, include_git: bool = True) -> dict:
    """Scan project for AI-generated code and assess governance.

    IMPORTANT: This scanner detects EXPLICIT markers only.
    It does not use stylistic heuristics, which have high
    false-positive rates. Absence of markers does not mean
    code is human-written.

    Returns:
        Dict with markers_found, tool_configs, git_signals,
        governance_status, summary, and limitations.
    """
    markers_found = []
    total_files = 0

    for rel_path, abs_path in _walk_code_files(project_path):
        total_files += 1
        content = _read_file(abs_path)
        if content is None:
            continue
        markers_found.extend(_scan_file_for_markers(content, rel_path))

    tool_configs = _detect_tool_configs(project_path)

    git_signals = []
    if include_git:
        git_signals = _scan_git_log(project_path)

    governance = _assess_governance(project_path)

    generators = sorted(set(
        [m["generator"] for m in markers_found]
        + [t["tool"] for t in tool_configs]
        + [g["generator"] for g in git_signals]
    ))

    files_with_markers = len(set(m["file"] for m in markers_found))

    return {
        "markers_found": markers_found,
        "tool_configs": tool_configs,
        "git_signals": git_signals,
        "governance_status": governance,
        "summary": {
            "generators_detected": generators,
            "files_with_markers": files_with_markers,
            "total_files_scanned": total_files,
            "governance_score": governance["score"],
            "transparency_compliant": governance["has_ai_policy"] and governance["has_disclosure"],
        },
        "limitations": (
            "This scanner detects explicit markers only. "
            "AI-generated code without markers will not be detected. "
            "For comprehensive tracking, implement a code provenance policy."
        ),
    }


# ---------------------------------------------------------------------------
# Text formatter
# ---------------------------------------------------------------------------

def format_ai_codegen_text(result: dict) -> str:
    """Format scan results as human-readable text."""
    lines = []
    summary = result["summary"]
    gov = result["governance_status"]

    # Header
    lines.append("=" * 60)
    lines.append("AI-Generated Code Governance Report")
    lines.append("=" * 60)
    lines.append("")

    # Generators detected
    if summary["generators_detected"]:
        gen_list = ", ".join(summary["generators_detected"])
        lines.append(f"AI Code Generators Detected: {gen_list}")
        lines.append(f"  Files with explicit markers: {summary['files_with_markers']}")
        lines.append(f"  Total files scanned: {summary['total_files_scanned']}")
    else:
        lines.append("No AI code generators detected (explicit markers only).")
        lines.append(f"  Total files scanned: {summary['total_files_scanned']}")
    lines.append("")

    # Markers
    if result["markers_found"]:
        lines.append("--- Explicit Markers Found ---")
        for m in result["markers_found"]:
            lines.append(f"  {m['file']}:{m['line']} [{m['generator']}] {m['marker_text']}")
        lines.append("")

    # Tool configs
    if result["tool_configs"]:
        lines.append("--- AI Tool Configurations ---")
        for t in result["tool_configs"]:
            lines.append(f"  {t['config_path']} ({t['tool']} — {t['provider']})")
        lines.append("")

    # Git signals
    if result["git_signals"]:
        lines.append("--- Git Commit Signals ---")
        for g in result["git_signals"]:
            lines.append(f"  {g['commit']}: [{g['generator']}] {g['message_excerpt']}")
        lines.append("")

    # Governance score
    score = gov["score"]
    if score >= 70:
        score_label = "GOOD"
    elif score >= 40:
        score_label = "PARTIAL"
    else:
        score_label = "LOW"
    lines.append(f"Governance Score: {score}/100 ({score_label})")
    lines.append(f"  AI usage policy:    {'Yes' if gov['has_ai_policy'] else 'No'}")
    lines.append(f"  AI code disclosure: {'Yes' if gov['has_disclosure'] else 'No'}")
    lines.append(f"  Model card:         {'Yes' if gov['has_model_card'] else 'No'}")
    lines.append(f"  Tool inventory:     {'Yes' if gov['has_tool_inventory'] else 'No'}")
    lines.append("")

    # Transparency compliance
    if summary["transparency_compliant"]:
        lines.append("EU AI Act Transparency (Art 50/52): COMPLIANT")
        lines.append("  AI usage policy and disclosure documentation found.")
    else:
        lines.append("EU AI Act Transparency (Art 50/52): GAPS FOUND")
        if not gov["has_ai_policy"]:
            lines.append("  Missing: AI usage policy — create docs/AI_USAGE_POLICY.md documenting")
            lines.append("    which AI tools are used, for what purposes, and review procedures.")
        if not gov["has_disclosure"]:
            lines.append("  Missing: AI code disclosure — create docs/AI_DISCLOSURE.md listing")
            lines.append("    AI-generated or AI-assisted code with provenance information.")
    lines.append("")

    # Recommendations
    recommendations = []
    if not gov["has_ai_policy"]:
        recommendations.append("Create docs/AI_USAGE_POLICY.md with: approved tools, usage guidelines, review requirements.")
    if not gov["has_disclosure"]:
        recommendations.append("Create docs/AI_DISCLOSURE.md with: list of AI-generated files, generator used, date, reviewer.")
    if not gov["has_model_card"]:
        recommendations.append("Create docs/MODEL_CARD.md if deploying ML models (dataset, performance, limitations).")
    if not gov["has_tool_inventory"]:
        recommendations.append("Create docs/AI_TOOLS.md with: inventory of AI tools, versions, configurations.")
    if summary["generators_detected"] and not gov["has_ai_policy"]:
        recommendations.append("AI tools are in use but no governance policy exists. This is a transparency gap under Art 50.")

    if recommendations:
        lines.append("--- Recommendations ---")
        for i, rec in enumerate(recommendations, 1):
            lines.append(f"  {i}. {rec}")
        lines.append("")

    # Limitations
    lines.append("--- Limitations ---")
    lines.append(f"  {result['limitations']}")
    lines.append("")

    return "\n".join(lines)
