# regula-ignore
"""
AI-Generated Code Governance Scanner for Regula.

Detects EXPLICIT markers of AI-generated code in a project and assesses
governance documentation quality. This scanner looks for comments, metadata,
tool configurations, and git commit signals that indicate AI tool usage.

IMPORTANT LIMITATION: This scanner detects explicit markers only (comments,
config files, commit messages). It does NOT use stylistic heuristics, which
have unacceptable false-positive rates. Absence of markers does NOT mean
code is human-written. For comprehensive provenance tracking, implement a
code provenance policy.

Relevant EU AI Act articles:
- Article 50: Transparency obligations for AI-generated content
- Article 52: Disclosure requirements for AI-generated content

No external dependencies — stdlib only.
"""

import re
import subprocess
import sys
from pathlib import Path

_scripts_dir = str(Path(__file__).parent)
if _scripts_dir not in sys.path:
    sys.path.insert(0, _scripts_dir)

from constants import CODE_EXTENSIONS, SKIP_DIRS
from scan_safety import walk_project_files  # shared path guard


# ---------------------------------------------------------------------------
# Explicit generator markers (HIGH confidence)
# ---------------------------------------------------------------------------

EXPLICIT_MARKERS = {
    "github_copilot": {
        "patterns": [
            r"# Generated by GitHub Copilot",
            r"// Generated by GitHub Copilot",
            r"@copilot-generated",
            r"copilot\.generated",
            r"GitHub Copilot.*suggestion",
        ],
        "generator": "GitHub Copilot",
        "provider": "Microsoft/GitHub",
    },
    "claude": {
        "patterns": [
            r"# Generated (?:by|with|using) Claude",
            r"// Generated (?:by|with|using) Claude",
            r"Co-Authored-By:.*Claude",
            r"anthropic.*generated",
            r"@claude-generated",
        ],
        "generator": "Claude",
        "provider": "Anthropic",
    },
    "chatgpt": {
        "patterns": [
            r"# Generated (?:by|with|using) (?:ChatGPT|GPT-4|GPT-3)",
            r"// Generated (?:by|with|using) (?:ChatGPT|GPT-4|GPT-3)",
            r"openai.*generated",
            r"@chatgpt-generated",
        ],
        "generator": "ChatGPT",
        "provider": "OpenAI",
    },
    "cursor": {
        "patterns": [
            r"# Generated (?:by|with|using) Cursor",
            r"// Generated (?:by|with|using) Cursor",
            r"cursor\.ai.*generated",
        ],
        "generator": "Cursor",
        "provider": "Anysphere",
    },
    "codewhisperer": {
        "patterns": [
            r"# Generated (?:by|with|using) (?:CodeWhisperer|Amazon Q)",
            r"// Generated (?:by|with|using) (?:CodeWhisperer|Amazon Q)",
        ],
        "generator": "Amazon Q Developer",
        "provider": "AWS",
    },
    "gemini_code": {
        "patterns": [
            r"# Generated (?:by|with|using) Gemini",
            r"// Generated (?:by|with|using) Gemini",
            r"google.*gemini.*generated",
        ],
        "generator": "Gemini Code Assist",
        "provider": "Google",
    },
}


# ---------------------------------------------------------------------------
# Tool configuration files (HIGH confidence)
# ---------------------------------------------------------------------------

TOOL_CONFIGS = [
    {"path": ".github/copilot-instructions.md", "tool": "GitHub Copilot", "provider": "Microsoft/GitHub"},
    {"path": ".cursorrules", "tool": "Cursor", "provider": "Anysphere"},
    {"path": ".cursor/rules", "tool": "Cursor", "provider": "Anysphere"},
    {"path": "CLAUDE.md", "tool": "Claude Code", "provider": "Anthropic"},
    {"path": ".claudeignore", "tool": "Claude Code", "provider": "Anthropic"},
    {"path": ".aider.conf.yml", "tool": "Aider", "provider": "Aider"},
    {"path": ".coderabbit.yaml", "tool": "CodeRabbit", "provider": "CodeRabbit"},
    {"path": ".continue/config.json", "tool": "Continue.dev", "provider": "Continue"},
    {"path": ".amazonq", "tool": "Amazon Q Developer", "provider": "AWS"},
]


# ---------------------------------------------------------------------------
# Git commit patterns (MEDIUM confidence)
# ---------------------------------------------------------------------------

GIT_COMMIT_PATTERNS = [
    {"pattern": r"Co-Authored-By:.*Claude", "generator": "Claude"},
    {"pattern": r"Co-Authored-By:.*GitHub Copilot", "generator": "GitHub Copilot"},
    {"pattern": r"Co-Authored-By:.*ChatGPT", "generator": "ChatGPT"},
    {"pattern": r"\[AI-generated\]", "generator": "Unknown AI"},
    {"pattern": r"\[copilot\]", "generator": "GitHub Copilot"},
    {"pattern": r"\[claude\]", "generator": "Claude"},
    {"pattern": r"\[chatgpt\]", "generator": "ChatGPT"},
    {"pattern": r"aider:", "generator": "Aider"},
]


# ---------------------------------------------------------------------------
# Governance documentation patterns
# ---------------------------------------------------------------------------

POLICY_FILES = [
    "ai-policy.md", "AI_GOVERNANCE.md", "ai_governance.md",
    "AI_USAGE_POLICY.md", "ai-usage-policy.md",
    "docs/ai-policy.md", "docs/AI_GOVERNANCE.md",
    "docs/ai_governance.md", "docs/AI_USAGE_POLICY.md",
]

DISCLOSURE_FILES = [
    "AI_DISCLOSURE.md", "ai-disclosure.md",
    "docs/AI_DISCLOSURE.md", "docs/ai-disclosure.md",
    "ATTRIBUTION.md", "docs/ATTRIBUTION.md",
]

MODEL_CARD_FILES = [
    "MODEL_CARD.md", "model_card.md", "model-card.md",
    "docs/MODEL_CARD.md", "docs/model_card.md",
]

TOOL_INVENTORY_FILES = [
    "AI_TOOLS.md", "ai-tools.md", "docs/AI_TOOLS.md",
    "docs/ai-tools.md", "AI_INVENTORY.md",
]


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _walk_code_files(project_path: str):
    """Yield (relative_path, absolute_path, content) for code files.

    Content is read during the walk rather than handed back as a path for
    the caller to reopen. Collecting a path and reading it later re-resolves
    it from scratch, and between those two moments an ancestor directory can
    be swapped for a symlink — a race O_NOFOLLOW cannot close, because it
    guards only the final component. walk_project_files reads through a
    descriptor held on the parent directory, so the inode is pinned (#33).

    It also supplies the shared SKIP_DIRS pruning, symlink-escape
    containment, FIFO refusal and size capping that this walker previously
    had to remember to ask for separately.
    """
    project = Path(project_path).resolve()
    for filepath, raw in walk_project_files(
            project, extensions=CODE_EXTENSIONS, skip_dirs=SKIP_DIRS):
        try:
            rel = str(filepath.relative_to(project))
        except ValueError:
            rel = str(filepath)
        yield rel, str(filepath), raw.decode("utf-8", errors="ignore")


def _scan_file_for_markers(content: str, rel_path: str):
    """Scan file content for explicit AI generator markers."""
    findings = []
    lines = content.splitlines()
    for marker_id, marker_info in EXPLICIT_MARKERS.items():
        for pattern in marker_info["patterns"]:
            for line_num, line in enumerate(lines, 1):
                if re.search(pattern, line, re.IGNORECASE):
                    findings.append({
                        "file": rel_path,
                        "line": line_num,
                        "generator": marker_info["generator"],
                        "provider": marker_info["provider"],
                        "confidence": "high",
                        "marker_text": line.strip(),
                    })
    return findings


def _detect_tool_configs(project_path: str):
    """Check for AI tool configuration files/directories."""
    project = Path(project_path).resolve()
    found = []
    for cfg in TOOL_CONFIGS:
        target = project / cfg["path"]
        if target.exists():
            found.append({
                "tool": cfg["tool"],
                "config_path": cfg["path"],
                "provider": cfg["provider"],
            })
    return found


def _scan_git_log(project_path: str, max_commits: int = 200):
    """Scan recent git commits for AI-generated code signals."""
    signals = []
    try:
        result = subprocess.run(
            ["git", "log", f"--max-count={max_commits}", "--format=%H %s%n%b"],
            capture_output=True, text=True, timeout=10,
            cwd=project_path,
        )
        if result.returncode != 0:
            return signals
    except (FileNotFoundError, subprocess.TimeoutExpired, OSError):
        return signals

    return _parse_git_output(result.stdout)


def _parse_git_output(git_output: str):
    """Parse git log output for AI signals. Separated for testability."""
    signals = []
    current_hash = None
    for line in git_output.splitlines():
        parts = line.split(" ", 1)
        if len(parts) == 2 and len(parts[0]) == 40 and all(c in "0123456789abcdef" for c in parts[0]):
            current_hash = parts[0][:8]
        for gp in GIT_COMMIT_PATTERNS:
            if re.search(gp["pattern"], line, re.IGNORECASE):
                signals.append({
                    "commit": current_hash or "unknown",
                    "generator": gp["generator"],
                    "message_excerpt": line.strip()[:120],
                })
    return signals


def _assess_governance(project_path: str):
    """Assess governance documentation quality."""
    project = Path(project_path).resolve()

    def _any_exists(file_list):
        return any((project / f).exists() for f in file_list)

    has_policy = _any_exists(POLICY_FILES)
    has_disclosure = _any_exists(DISCLOSURE_FILES)
    has_model_card = _any_exists(MODEL_CARD_FILES)
    has_inventory = _any_exists(TOOL_INVENTORY_FILES)

    score = 0
    if has_policy:
        score += 40
    if has_disclosure:
        score += 30
    if has_model_card:
        score += 15
    if has_inventory:
        score += 15

    return {
        "has_ai_policy": has_policy,
        "has_disclosure": has_disclosure,
        "has_model_card": has_model_card,
        "has_tool_inventory": has_inventory,
        "score": score,
    }


# ---------------------------------------------------------------------------
# Main scanner
# ---------------------------------------------------------------------------

def scan_ai_generated_code(project_path: str, include_git: bool = True) -> dict:
    """Scan project for AI-generated code and assess governance.

    IMPORTANT: This scanner detects EXPLICIT markers only.
    It does not use stylistic heuristics, which have high
    false-positive rates. Absence of markers does not mean
    code is human-written.

    Returns:
        Dict with markers_found, tool_configs, git_signals,
        governance_status, summary, and limitations.
    """
    markers_found = []
    total_files = 0

    # total_files now counts files actually read. It previously counted
    # every code file yielded, including ones the read then refused, so a
    # tree with an unreadable file reported it as scanned. Identical on any
    # well-formed tree.
    for rel_path, _abs_path, content in _walk_code_files(project_path):
        total_files += 1
        markers_found.extend(_scan_file_for_markers(content, rel_path))

    tool_configs = _detect_tool_configs(project_path)

    git_signals = []
    if include_git:
        git_signals = _scan_git_log(project_path)

    governance = _assess_governance(project_path)

    generators = sorted(set(
        [m["generator"] for m in markers_found]
        + [t["tool"] for t in tool_configs]
        + [g["generator"] for g in git_signals]
    ))

    files_with_markers = len(set(m["file"] for m in markers_found))

    return {
        "markers_found": markers_found,
        "tool_configs": tool_configs,
        "git_signals": git_signals,
        "governance_status": governance,
        "summary": {
            "generators_detected": generators,
            "files_with_markers": files_with_markers,
            "total_files_scanned": total_files,
            "governance_score": governance["score"],
            # RENAMED 2026-08-17, . This key was
            # `transparency_compliant`, a JSON key asserting a compliance state
            # whose entire predicate is two files existing on disk. Neither file
            # is opened, and Article 50 governs how a system behaves towards the
            # people using it, not whether a repository contains documentation.
            # A key name is a claim: consumers read `transparency_compliant:
            # true` as a determination, and no disclaimer elsewhere in the
            # payload reaches them. The name now states the observable.
            #
            # This is a BREAKING change to the `ai-codegen` data payload and is
            # deliberately not aliased: keeping the old key would keep shipping
            # the claim this change exists to remove.
            "transparency_documents_present": (
                governance["has_ai_policy"] and governance["has_disclosure"]
            ),
        },
        "limitations": (
            "This scanner detects explicit markers only. "
            "AI-generated code without markers will not be detected. "
            "For comprehensive tracking, implement a code provenance policy."
        ),
    }


# ---------------------------------------------------------------------------
# Text formatter
# ---------------------------------------------------------------------------

def format_ai_codegen_text(result: dict) -> str:
    """Format scan results as human-readable text."""
    lines = []
    summary = result["summary"]
    gov = result["governance_status"]

    # Header
    lines.append("=" * 60)
    lines.append("AI-Generated Code Governance Report")
    lines.append("=" * 60)
    lines.append("")

    # Generators detected
    if summary["generators_detected"]:
        gen_list = ", ".join(summary["generators_detected"])
        lines.append(f"AI Code Generators Detected: {gen_list}")
        lines.append(f"  Files with explicit markers: {summary['files_with_markers']}")
        lines.append(f"  Total files scanned: {summary['total_files_scanned']}")
    else:
        lines.append("No AI code generators detected (explicit markers only).")
        lines.append(f"  Total files scanned: {summary['total_files_scanned']}")
    lines.append("")

    # Markers
    if result["markers_found"]:
        lines.append("--- Explicit Markers Found ---")
        for m in result["markers_found"]:
            lines.append(f"  {m['file']}:{m['line']} [{m['generator']}] {m['marker_text']}")
        lines.append("")

    # Tool configs
    if result["tool_configs"]:
        lines.append("--- AI Tool Configurations ---")
        for t in result["tool_configs"]:
            lines.append(f"  {t['config_path']} ({t['tool']} — {t['provider']})")
        lines.append("")

    # Git signals
    if result["git_signals"]:
        lines.append("--- Git Commit Signals ---")
        for g in result["git_signals"]:
            lines.append(f"  {g['commit']}: [{g['generator']}] {g['message_excerpt']}")
        lines.append("")

    # Documentation presence. Reported as a count of the four documents this
    # function looks for, NOT as a graded verdict.
    #
    # Until 2026-08-17 this printed "Governance Score: 70/100 (GOOD)". Both
    # halves were unsupportable from the same predicate: GOOD/PARTIAL/LOW passes
    # a quality judgement on a project's governance, and an N/100 score invites
    # reading a documentation-presence tally as a governance measurement, when
    # what was measured is whether four filenames exist. The four booleans below
    # were always the honest content of this block. .
    score = gov["score"]
    present = sum(1 for k in ("has_ai_policy", "has_disclosure",
                              "has_model_card", "has_tool_inventory") if gov[k])
    lines.append(f"Governance documents present: {present} of 4")
    lines.append(f"  (file-presence score {score}/100; no file is read, and "
                 f"presence is not compliance)")
    lines.append(f"  AI usage policy:    {'Yes' if gov['has_ai_policy'] else 'No'}")
    lines.append(f"  AI code disclosure: {'Yes' if gov['has_disclosure'] else 'No'}")
    lines.append(f"  Model card:         {'Yes' if gov['has_model_card'] else 'No'}")
    lines.append(f"  Tool inventory:     {'Yes' if gov['has_tool_inventory'] else 'No'}")
    lines.append("")

    # Article 50/52 transparency DOCUMENTS, reported as file presence.
    #
    # Until 2026-08-17 this printed the Article 50/52 heading followed by a
    # capitalised compliance state.  carries the verbatim string;
    # it is not quoted here, because quoting it reintroduces it. Reproduced then
    # on a project created by two `echo` commands totalling 34 bytes, which is
    # the whole of the evidence the claim rested on.
    # Article 50 duties attach to disclosing AI interaction and marking
    # synthetic content in the running system; no arrangement of files in a
    # repository can discharge them, and this function does not read the files
    # it counts. .
    if summary["transparency_documents_present"]:
        lines.append("Article 50/52 transparency documents: both present")
        lines.append("  An AI usage policy and an AI code disclosure file were found.")
        lines.append("  Neither was read. Presence of a document is not compliance")
        lines.append("  with Article 50, which governs system behaviour.")
    else:
        lines.append("Article 50/52 transparency documents: not both present")
        if not gov["has_ai_policy"]:
            lines.append("  Missing: AI usage policy — create docs/AI_USAGE_POLICY.md documenting")
            lines.append("    which AI tools are used, for what purposes, and review procedures.")
        if not gov["has_disclosure"]:
            lines.append("  Missing: AI code disclosure — create docs/AI_DISCLOSURE.md listing")
            lines.append("    AI-generated or AI-assisted code with provenance information.")
    lines.append("")

    # Recommendations
    recommendations = []
    if not gov["has_ai_policy"]:
        recommendations.append("Create docs/AI_USAGE_POLICY.md with: approved tools, usage guidelines, review requirements.")
    if not gov["has_disclosure"]:
        recommendations.append("Create docs/AI_DISCLOSURE.md with: list of AI-generated files, generator used, date, reviewer.")
    if not gov["has_model_card"]:
        recommendations.append("Create docs/MODEL_CARD.md if deploying ML models (dataset, performance, limitations).")
    if not gov["has_tool_inventory"]:
        recommendations.append("Create docs/AI_TOOLS.md with: inventory of AI tools, versions, configurations.")
    if summary["generators_detected"] and not gov["has_ai_policy"]:
        recommendations.append("AI tools are in use but no governance policy exists. This is a transparency gap under Art 50.")

    if recommendations:
        lines.append("--- Recommendations ---")
        for i, rec in enumerate(recommendations, 1):
            lines.append(f"  {i}. {rec}")
        lines.append("")

    # Limitations
    lines.append("--- Limitations ---")
    lines.append(f"  {result['limitations']}")
    lines.append("")

    return "\n".join(lines)
