#!/usr/bin/env python3
"""Render the published comparison table from its single source of truth.

`data/comparison_table.json` holds the table. This module renders it into the
three shipped homepages between `COMPARISON:BEGIN` and `COMPARISON:END`
markers. The shipped HTML is generated, never hand-edited, which is the same
rule `site/regions/` follows and for the same reason: three hand-maintained
copies of one table drift, and the drift is silent.

Three checks live here because a comparison table is a claim surface:

- `--check` re-renders and fails on any difference from the shipped files, so
  a hand edit cannot survive CI.
- `--check-freshness` fails when `verified_on` is older than `max_age_days`.
  A competitor comparison rots: prices and features change under us, and a
  stale table is a wrong claim about a named third party.
- `unverified_cells()` enumerates every cell we could not establish from a
  primary source, so the count is produced by the data and never by hand.

Fairness is a requirement, not a preference. A UK comparison must be
objective, verifiable and representative, must not mislead and must not
denigrate. Cells state what a provider's own page says, or say
`not verified`. They do not characterise a competitor.
"""
from __future__ import annotations

import argparse
import json
import sys
from datetime import date, timedelta
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))

REPO_ROOT = Path(__file__).resolve().parent.parent
DATA = REPO_ROOT / "data" / "comparison_table.json"

BEGIN = "<!-- COMPARISON:BEGIN generated by scripts/build_comparison.py -->"
END = "<!-- COMPARISON:END -->"

NOT_VERIFIED = "not verified"

SOURCES_LABEL = {
    "en": "Sources checked",
    "de": "Geprüfte Quellen",
    "pt": "Fontes consultadas",
}
SOURCES_NONE = {
    "en": "none checked this round",
    "de": "in dieser Runde keine geprüft",
    "pt": "nenhuma consultada nesta ronda",
}


def _host(url: str) -> str:
    """Display host plus first path segment, so a link is readable in a cell."""
    rest = url.split("://", 1)[-1].rstrip("/")
    parts = rest.split("/")
    host = parts[0]
    return f"{host}/{parts[1]}" if len(parts) > 1 and parts[1] else host

# locale key -> shipped file.
#
# Moved off the three homepages on 2026-08-18 (LEDGER N176). The comparison is
# product detail, not a routing decision, and it went to the product page with
# the rest of it. This map is the generator's only statement of where the table
# lives; tests/test_comparison_table.py checks the shipped pages against a fresh
# render, so a stale entry here fails rather than silently leaving a table
# behind on a page that no longer wants one.
TARGETS = {
    "en": REPO_ROOT / "site" / "product.html",
    "de": REPO_ROOT / "site" / "product-de.html",
    "pt": REPO_ROOT / "site" / "product-pt-br.html",
}


def load() -> dict:
    return json.loads(DATA.read_text(encoding="utf-8"))


def _esc(text: str) -> str:
    """Escape markup, then fold non-ASCII to entities.

    The locale pages are written with HTML entities for accented characters,
    so rendered cells match the surrounding file rather than introducing a
    second convention into the same document.
    """
    out = (text.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
           .replace('"', "&quot;"))
    return out.encode("ascii", "xmlcharrefreplace").decode("ascii")


def unverified_cells(data: dict | None = None) -> list[str]:
    """Every `row.column` whose English cell is the not-verified marker.

    Produced by enumeration rather than by reading the table, because a
    hand-built list of "everything unverified" is exactly the completeness
    claim measurement rule 4c forbids.
    """
    data = data or load()
    out = []
    for row in data["rows"]:
        for col in data["columns"]:
            cell = row["cells"][col["key"]]
            if cell["en"].strip().lower() == NOT_VERIFIED:
                out.append(f"{row['key']}.{col['key']}")
    return sorted(out)


def render(locale: str, data: dict | None = None) -> str:
    data = data or load()
    stamp = data["verified_on"]
    cols = data["columns"]

    head = "".join(
        f'<th scope="col" style="padding:8px 12px;">{_esc(c["label"])}</th>'
        for c in cols
    )

    body = []
    for i, row in enumerate(data["rows"]):
        shade = ' style="background:#0d0d1a;"' if i % 2 else ""
        cells = "".join(
            f'<td style="padding:6px 12px;">{_esc(row["cells"][c["key"]][locale])}</td>'
            for c in cols
        )
        body.append(
            f'<tr{shade}><th scope="row" style="padding:6px 12px;color:#e0e0f0;'
            f'font-weight:400;text-align:left;">{_esc(row["label"][locale])}</th>'
            f"{cells}</tr>"
        )

    # A sources row, not a footnote. The UK standard requires a comparison to
    # be verifiable, and the claim auditor requires a reference in the same
    # paragraph as an attributed statement. Rendering each column's primary
    # sources inside the table satisfies both, and lets a reader check a cell
    # without leaving the page.
    src_cells = []
    for c in cols:
        urls = data["sources"].get(c["key"], [])
        if not urls:
            src_cells.append(
                '<td style="padding:6px 12px;">'
                f"{_esc(SOURCES_NONE[locale])}</td>"
            )
            continue
        links = " ".join(
            f'<a href="{_esc(u)}" rel="nofollow noopener" '
            f'style="color:inherit;">{_esc(_host(u))}</a>'
            for u in urls
        )
        src_cells.append(f'<td style="padding:6px 12px;">{links}</td>')
    sources_row = (
        '<tr><th scope="row" style="padding:6px 12px;color:#e0e0f0;'
        f'font-weight:400;text-align:left;">{_esc(SOURCES_LABEL[locale])}</th>'
        + "".join(src_cells) + "</tr>"
    )
    body.append(sources_row)

    caveat = _esc(data["caveat"][locale].replace("{date}", stamp))
    caption = _esc(data["caption"][locale])
    stamp_label = _esc(data["stamp_label"][locale])

    return (
        f"{BEGIN}\n"
        f'<div role="region" aria-label="{_esc(data["aria_label"][locale])}" '
        f'style="overflow-x:auto;margin-top:32px;'
        f'-webkit-overflow-scrolling:touch;">\n'
        f'<p class="scroll-hint" style="display:none;font-size:11px;'
        f'color:var(--text-dim);margin-bottom:8px;text-align:right;">'
        f"Scroll &rarr;</p>\n"
        f'<table class="cmp-table" style="width:100%;border-collapse:collapse;'
        f'font-size:13px;color:#b0b0cc;">\n'
        f'<caption class="sr-only">{caption}</caption>\n'
        f'<thead><tr style="border-bottom:1px solid #23234a;text-align:left;">'
        f'<th scope="col" style="padding:8px 12px;">'
        f'<span class="sr-only">Feature</span></th>{head}</tr></thead>\n'
        f"<tbody>\n" + "\n".join(body) + "\n</tbody>\n</table>\n"
        f'<p style="font-size:12px;color:var(--text-dim);margin-top:12px;">'
        f"<strong>{stamp_label}: {stamp}</strong></p>\n"
        f'<p style="font-size:12px;color:var(--text-dim);margin-top:8px;">'
        f"{caveat}</p>\n"
        f"</div>\n"
        f"{END}"
    )


def _splice(text: str, block: str) -> str:
    start = text.index(BEGIN)
    stop = text.index(END) + len(END)
    return text[:start] + block + text[stop:]


def apply() -> list[str]:
    data = load()
    changed = []
    for locale, path in TARGETS.items():
        current = path.read_text(encoding="utf-8")
        updated = _splice(current, render(locale, data))
        if updated != current:
            path.write_text(updated, encoding="utf-8")
            changed.append(str(path.relative_to(REPO_ROOT)))
    return changed


def check() -> list[str]:
    """Return the files whose shipped block differs from a fresh render."""
    data = load()
    drifted = []
    for locale, path in TARGETS.items():
        current = path.read_text(encoding="utf-8")
        if BEGIN not in current or END not in current:
            drifted.append(f"{path.relative_to(REPO_ROOT)}: markers missing")
            continue
        start = current.index(BEGIN)
        stop = current.index(END) + len(END)
        if current[start:stop] != render(locale, data):
            drifted.append(str(path.relative_to(REPO_ROOT)))
    return drifted


def freshness_error(today: date | None = None, data: dict | None = None) -> str | None:
    """Return an error string when the stamp is too old, else None."""
    data = data or load()
    today = today or date.today()
    stamped = date.fromisoformat(data["verified_on"])
    max_age = int(data["max_age_days"])
    age = (today - stamped).days
    if age > max_age:
        expired = stamped + timedelta(days=max_age)
        return (
            f"comparison table stamp is {age} days old "
            f"(verified_on {stamped.isoformat()}, limit {max_age} days, "
            f"expired {expired.isoformat()}). Re-verify every cell against "
            f"each provider's own site and update verified_on."
        )
    if age < 0:
        return (
            f"comparison table verified_on {stamped.isoformat()} is in the "
            f"future relative to {today.isoformat()}"
        )
    return None


def main(argv: list[str] | None = None) -> int:
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("--apply", action="store_true",
                   help="write the rendered table into the shipped pages")
    p.add_argument("--check", action="store_true",
                   help="fail if any shipped block differs from a fresh render")
    p.add_argument("--check-freshness", action="store_true",
                   help="fail if verified_on is older than max_age_days")
    p.add_argument("--today", metavar="YYYY-MM-DD",
                   help="evaluate freshness as at this date (for testing)")
    p.add_argument("--list-unverified", action="store_true",
                   help="print every cell marked not verified")
    args = p.parse_args(argv)

    data = load()

    if args.list_unverified:
        cells = unverified_cells(data)
        print(f"unverified cells: {len(cells)}")
        for c in cells:
            print(f"  {c}")
        return 0

    if args.apply:
        changed = apply()
        print(f"comparison: rendered into {len(TARGETS)} page(s)")
        for c in changed:
            print(f"  updated {c}")
        if not changed:
            print("  all pages already current")
        return 0

    if args.check_freshness:
        today = date.fromisoformat(args.today) if args.today else None
        err = freshness_error(today, data)
        if err:
            print(f"comparison-freshness: FAIL: {err}", file=sys.stderr)
            return 1
        stamped = date.fromisoformat(data["verified_on"])
        ref = today or date.today()
        print(
            f"comparison-freshness: OK, stamp {data['verified_on']} is "
            f"{(ref - stamped).days} day(s) old, limit {data['max_age_days']}"
        )
        return 0

    if args.check:
        drifted = check()
        if drifted:
            print("comparison: shipped HTML differs from the source of truth:",
                  file=sys.stderr)
            for d in drifted:
                print(f"  {d}", file=sys.stderr)
            print("  run: python3 scripts/build_comparison.py --apply",
                  file=sys.stderr)
            return 1
        print(f"comparison: all {len(TARGETS)} page(s) match the source")
        print(f"comparison: {len(unverified_cells(data))} cell(s) marked "
              f"'{NOT_VERIFIED}'")
        return 0

    p.print_help()
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
