#!/usr/bin/env python3
# regula-ignore — this builder embeds public detector documentation but implements no regulated practice
"""Build the long-form LLM discovery surface from authoritative documents."""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))

ROOT = Path(__file__).resolve().parents[1]
OUTPUT = ROOT / "site" / "llms-full.txt"
SECTIONS = (
    ("README", ROOT / "README.md"),
    ("Scope and limitations", ROOT / "docs" / "what-regula-does-not-do.md"),
    ("Quick start", ROOT / "docs" / "QUICKSTART.md"),
    ("Installation", ROOT / "docs" / "installation.md"),
)

HEADER = """# Regula — full context for LLM agents

> Regula reports code-observable AI-governance indicators and records declared deployment context for human review. It does not determine legal classification or compliance. The current public distribution is source-only while PyPI and the public website are unavailable; see the installation section below.

This file is generated by `python3 scripts/build_llms_full.py`. Edit the source documents, not the copied sections here.
"""

TRAILER = """## Evaluation evidence

The repository retains dated benchmark methodology and raw artefacts under `docs/benchmarks/` and `benchmarks/`. Superseded figures are not copied into this current public-discovery surface because they could be mistaken for current validity claims. Start with `docs/VALIDITY_UX_ENGINEERING_AUDIT_2026-08-26.md` and `docs/improvement/STATE.md`, then inspect the underlying labelled records. The external corpus is single-rater and current precision/recall is not independently established.

One retained April 2026 library-corpus result is 15.2% precision (39 true positives and 218 false positives, N=257). It is a single-reviewer labelled-finding sample with no inter-rater agreement, not a project-level accuracy estimate and not evidence of current general precision. Reproduce that recorded subset with `python3 benchmarks/label.py score --corpus library`.
"""


def render() -> str:
    """Return the deterministic full-context document."""
    chunks = [HEADER.rstrip()]
    for title, path in SECTIONS:
        body = path.read_text(encoding="utf-8").strip()
        chunks.append(f"## {title}\n\n{body}")
    chunks.append(TRAILER.rstrip())
    return "\n\n".join(chunks) + "\n"


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--check",
        action="store_true",
        help="fail if site/llms-full.txt differs from the generated content",
    )
    args = parser.parse_args(argv)
    expected = render()
    if args.check:
        if not OUTPUT.exists() or OUTPUT.read_text(encoding="utf-8") != expected:
            print("site/llms-full.txt is stale; run python3 scripts/build_llms_full.py", file=sys.stderr)
            return 1
        print("site/llms-full.txt is current")
        return 0
    OUTPUT.write_text(expected, encoding="utf-8")
    print(f"wrote {OUTPUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
