#!/usr/bin/env python3
"""Render the qualifier section into every locale page from one source.

WHY THIS IS GENERATED RATHER THAN HAND-WRITTEN. The qualifier is the first
view of three pages in three languages. Hand-maintaining three copies of the
same markup is the drift this project's own rules forbid
(.claude/rules/quality-standards.md: "a manually-maintained copy WILL drift
silently"), and locale-incomplete work is not acceptable. So the structure is
produced here, once, and the only thing that differs between the three pages is
the words, which live in data/qualifier_copy/*.json.

The single source of truth for every regulatory date is scripts/omnibus.py.
No date is written in prose anywhere: the copy tables carry ISO dates, the
browser renders them with the locale's own month names, and
tests/test_qualifier.py fails if a copy table and omnibus.py disagree.

Run after any change to the copy tables or to this file:

    python3 scripts/build_qualifier.py

tests/test_qualifier.py fails when the committed pages differ from a fresh
render, so a stale page cannot ship.
"""
from __future__ import annotations

import html
import json
import re
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))

REPO_ROOT = Path(__file__).resolve().parent.parent
COPY_DIR = REPO_ROOT / "data" / "qualifier_copy"
SITE_FACTS = REPO_ROOT / "data" / "site_facts.json"

# locale key -> page it renders into. Both halves are checked by the test:
# a page without markers and a copy table without a page both fail.
TARGETS = {
    "en": "site/index.html",
    "de": "site/locales/de.html",
    "pt-br": "site/locales/pt-br.html",
}

BEGIN = "<!-- QUALIFIER:BEGIN -->"
END = "<!-- QUALIFIER:END -->"

GENERATED_NOTE = (
    "<!-- Generated by scripts/build_qualifier.py from "
    "data/qualifier_copy/{key}.json. Do not edit between the markers by hand: "
    "tests/test_qualifier.py compares the committed page against a fresh "
    "render and fails on any difference. -->"
)


def canonical_test_count() -> int:
    """The collected-test total, read from the artefact that generates it.

    Never hand-authored and never cascaded into this block as a literal. A
    literal here would be a fourth carrier for a number that has already drifted
    across surfaces in this programme (measurement rule 3), and
    tests/test_qualifier.py compares the committed page against a fresh render,
    so a stale figure fails rather than ships.
    """
    facts = json.loads(SITE_FACTS.read_text(encoding="utf-8"))
    return int(facts["counts"]["tests"]["total_collected"])


def group(number: int, separator: str) -> str:
    return f"{number:,}".replace(",", separator)


def esc(text: str) -> str:
    return html.escape(str(text), quote=True)


def _question(index: int, q: dict) -> str:
    qid = esc(q["id"])
    options = "\n".join(
        f'            <span class="qual-opt">'
        f'<input type="radio" id="qual-{qid}-{esc(o["value"])}" '
        f'name="{qid}" value="{esc(o["value"])}">'
        f'<label class="qual-face" for="qual-{qid}-{esc(o["value"])}">'
        f'{esc(o["label"])}</label></span>'
        for o in q["options"]
    )
    return (
        f'      <li class="qual-q" id="qual-{qid}">\n'
        f'        <fieldset>\n'
        f'          <legend><span class="qual-n" aria-hidden="true">'
        f'{index}/5</span>{esc(q["legend"])}</legend>\n'
        f'          <p class="qual-help">{esc(q["help"])}</p>\n'
        f'          <div class="qual-opts">\n{options}\n          </div>\n'
        f'        </fieldset>\n'
        f'      </li>'
    )


def render(key: str, copy: dict) -> str:
    questions = "\n".join(
        _question(i + 1, q) for i, q in enumerate(copy["questions"])
    )
    def _lang_attr(href: str) -> str:
        """hreflang for a cross-language link, computed outside the f-string.

        A backslash escape inside an f-string is a syntax error before Python
        3.12 and this project supports 3.10. Ruff caught it; only 3.12 exists
        on the machine this was written on, so nothing else would have.
        """
        if copy["lang"] == "en" or not href.startswith("/"):
            return ""
        return ' hreflang="en"'

    nojs_items = "\n".join(
        f'        <li><a href="{esc(item["href"])}"{_lang_attr(item["href"])}>'
        f'{esc(item["text"])}</a></li>'
        for item in copy["nojsItems"]
    )
    # Every target is English. On a localised page the link declares the change
    # of language, machine-readably here and visibly in the copy table, which is
    # what scripts/locale_link_audit.py enforces across the site.
    hl = "" if copy["lang"] == "en" else ' hreflang="en"'
    cue = esc(copy["englishOnlyCue"])
    cue = f" {cue}" if cue else ""
    shorts = "\n".join(
        f'      <li><a href="{esc(copy["routes"][k]["href"])}"{hl}>'
        f'{esc(copy["routes"][k]["title"])}{cue}</a>. '
        f'{esc(copy["routes"][k]["short"])}</li>'
        for k in ("free", "paid", "consultant")
    )
    # `</` is escaped so the blob can never terminate its own <script>.
    blob = json.dumps(copy, ensure_ascii=False, sort_keys=True).replace("</", "<\\/")

    return f"""{BEGIN}
{GENERATED_NOTE.format(key=key)}
<section class="qual-wrap" aria-labelledby="qual-h1">
  <div class="qual">
    <h1 id="qual-h1">{esc(copy["h1"])}</h1>
    <p class="qual-sub">{esc(copy["sub"])}</p>
    <p class="qual-meta">{esc(copy["meta"])}</p>

    <form id="qual-form" novalidate>
      <ol class="qual-qs">
{questions}
      </ol>
      <p class="qual-err" id="qual-error" role="alert" hidden></p>
      <div class="qual-actions">
        <button type="submit" class="qual-go">{esc(copy["submit"])}</button>
        <button type="button" class="qual-quiet" id="qual-reset">{esc(copy["reset"])}</button>
      </div>
    </form>

    <div class="qual-nojs" id="qual-nojs" role="note">
      <p>{esc(copy["nojsTitle"])}</p>
      <p>{esc(copy["nojsLead"])}</p>
      <ul>
{nojs_items}
      </ul>
    </div>

    <div class="qual-result" id="qual-result" hidden></div>

    <h2 class="qual-after-h">{esc(copy["afterHeading"])}</h2>
    <p class="qual-meta">{esc(copy["afterLead"])}</p>
    <ul class="qual-unsettled">
{shorts}
    </ul>
  </div>
</section>
<script type="application/json" id="qual-copy">{blob}</script>
<script src="/assets/qualifier.js" defer></script>
{END}"""


def apply_to_page(page_text: str, key: str, copy: dict) -> str:
    """Replace the marked block and the developer-entry headings."""
    start = page_text.index(BEGIN)
    stop = page_text.index(END) + len(END)
    out = page_text[:start] + render(key, copy) + page_text[stop:]

    # Drop any previously generated proof strip before re-inserting, so the
    # whole operation is idempotent and a copy change does not leave two.
    out = re.sub(r'\n\s*<ul class="qual-proof">.*?</ul>', "", out, flags=re.DOTALL)

    section = re.search(
        r'(<div class="sec reveal" id="terminal">\s*\n\s*<h2 class="sec-head">)'
        r'(.*?)(</h2>\s*\n\s*<p class="sec-sub">)(.*?)(</p>)',
        out, re.DOTALL)
    if not section:
        raise RuntimeError(f"{key}: developer-entry section not found")

    proof = copy["proof"]
    tests = esc(proof["tests"]).replace(
        "{tests}", group(canonical_test_count(), copy["thousandsSep"]))
    strip = (
        '\n    <ul class="qual-proof">'
        f'<li>{tests}</li>'
        f'<li>{esc(proof["security"])}</li>'
        f'<li>{esc(proof["deps"])}</li>'
        f'<li>{esc(proof["upload"])}</li>'
        f'<li><a href="{esc(proof["trustHref"])}">{esc(proof["trustLabel"])}</a></li>'
        '</ul>')
    return (out[:section.start()]
            + section.group(1) + esc(copy["devHeading"])
            + section.group(3) + esc(copy["devBody"]) + section.group(5)
            + strip
            + out[section.end():])


def build(write: bool = True) -> dict[str, str]:
    """Return {page path: rendered page text}. Writes unless write=False."""
    rendered = {}
    for key, rel in TARGETS.items():
        copy = json.loads((COPY_DIR / f"{key}.json").read_text(encoding="utf-8"))
        page = REPO_ROOT / rel
        text = apply_to_page(page.read_text(encoding="utf-8"), key, copy)
        rendered[rel] = text
        if write and text != page.read_text(encoding="utf-8"):
            page.write_text(text, encoding="utf-8")
            print(f"{rel}: rewritten")
        elif write:
            print(f"{rel}: already current")
    return rendered


if __name__ == "__main__":
    build()
