#!/usr/bin/env python3
"""Generate the browser decision-model module from the canonical JSON file."""

import json
from pathlib import Path


ROOT = Path(__file__).resolve().parent.parent
SOURCE = ROOT / "references" / "decision_model.v1.json"
TARGET = ROOT / "site" / "assess" / "decision-model.js"


def render():
    model = json.loads(SOURCE.read_text(encoding="utf-8"))
    payload = json.dumps(model, ensure_ascii=False, separators=(",", ":"))
    return (
        "// regula-ignore: * -- generated regulatory rule descriptions, not an implementation of a prohibited practice\n"
        "// Generated by scripts/build_browser_decision_model.py. Do not edit.\n"
        "(function (root, factory) {\n"
        "  const model = factory();\n"
        "  if (typeof module === 'object' && module.exports) module.exports = model;\n"
        "  root.RegulaDecisionModel = model;\n"
        "})(typeof globalThis !== 'undefined' ? globalThis : this, function () {\n"
        f"  return {payload};\n"
        "});\n"
    )


def main():
    TARGET.write_text(render(), encoding="utf-8")
    print(f"generated {TARGET.relative_to(ROOT)} from {SOURCE.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
