#!/usr/bin/env python3
"""Render the programme's current, reproducible resume state."""
from __future__ import annotations

import argparse
import json
import re
import subprocess
import sys
from collections import Counter
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))

import ledger_review
import ledger_status

REPO_ROOT = Path(__file__).resolve().parent.parent
STATE_PATH = REPO_ROOT / "docs" / "improvement" / "STATE.md"
MANIFEST = REPO_ROOT / "benchmarks" / "synthetic" / "manifest.json"
RECALL = REPO_ROOT / "benchmarks" / "synthetic" / "RECALL.json"


def _scanner_measurement() -> tuple[int, int, int, int, int]:
    manifest = json.loads(MANIFEST.read_text(encoding="utf-8"))
    expectations = manifest["expectations"]
    corpus = len(expectations)
    high_total = sum(value == "high_risk" for value in expectations.values())
    proc = subprocess.run(
        ["node", "tests/test_scanner_js.js"],
        cwd=REPO_ROOT,
        capture_output=True,
        text=True,
        timeout=120,
    )
    if proc.returncode:
        raise RuntimeError("JavaScript parity gate is red:\n" + proc.stdout + proc.stderr)
    summary = re.search(
        r"Label fidelity \(not real-world accuracy\): prohibited (\d+)/(\d+); "
        r"high-risk (\d+)/(\d+); negatives (\d+)/(\d+)",
        proc.stdout,
    )
    if not summary:
        raise RuntimeError("JavaScript parity gate emitted no parseable label summary")
    high_exact = int(summary.group(3))
    if int(summary.group(4)) != high_total:
        raise RuntimeError("parity summary and manifest disagree on high-risk total")
    return corpus, high_exact, high_total, int(summary.group(5)), int(summary.group(6))


def render() -> str:
    machine = ledger_status.parse()
    machine_counts = Counter(state for _nid, state in machine)
    legacy = ledger_status.legacy_classifications()
    legacy_counts = Counter(row["state"] for row in legacy)
    review_queue = ledger_review.review_queue()
    corpus, high_exact, high_total, negative_correct, negative_total = (
        _scanner_measurement())
    recall = json.loads(RECALL.read_text(encoding="utf-8"))
    default_recall = recall["conditions"]["scanner/default"]["tiers"][
        "high_risk"]["fraction"]

    return f"""# Regula — current resume state

<!-- Generated by scripts/current_state.py. Do not edit measured values by hand. -->

This file replaces the historical July narrative that previously presented
itself as current. The historical record remains in Git history and the detailed
chronology remains in `docs/improvement/LEDGER.md`. Regenerate this file with:

```bash
python3 scripts/current_state.py --write
python3 scripts/current_state.py --check
```

## Product task

The primary landing user is a non-technical founder or operator who needs to
work out whether AI regulation may reach their business and what to do next.
The homepage must support that task before presenting the developer CLI.

## Reproducible current measurements

- Machine-state ledger: {len(machine)} entries = {machine_counts['OPEN']} OPEN + {machine_counts['PARTIAL']} PARTIAL + {machine_counts['CLOSED']} CLOSED.
- Anything outstanding in that population: {machine_counts['OPEN'] + machine_counts['PARTIAL']} entries; substantively unfinished: {machine_counts['OPEN']}.
- Historical table: {len(legacy)} rows = {legacy_counts['OPEN']} OPEN + {legacy_counts['PARTIAL']} PARTIAL + {legacy_counts['CLOSED']} CLOSED + {legacy_counts['REVIEW_REQUIRED']} REVIEW_REQUIRED.
- Ledger review queue: {len(review_queue)} rows require independent human review; the bot does not infer their state.
- Browser/Python scanner parity gate: all {corpus} canonical fixtures execute, including all {high_total} high-risk fixtures.
- Synthetic label fidelity, not real-world accuracy: high-risk {high_exact}/{high_total}; negatives {negative_correct}/{negative_total}. The default CLI condition separately recalls {default_recall} high-risk fixtures.

## Current boundaries

- **Deployment currency is not derivable from this repository.** Compare the
  remote branch and the live `https://getregula.com/` response before saying the
  website is updated. A local or committed HTML change is not a deployment.
- **Scanner parity is not scanner validity.** Runtime agreement only shows that
  Python and browser implementations make the same decision. It does not show
  that the decision is correct or representative of real code.
- **The synthetic corpus is maintainer-authored.** It cannot establish
  real-world precision, recall, legal accuracy, or absence of bias.
- **Automated browser and accessibility checks are not usability evidence.**
  Representative founders must still test comprehension, confidence, and task
  completion.
- **Regulatory mappings still require qualified legal review.** The tool must
  keep unresolved facts unresolved.

## Resume order

1. Keep the complete scanner parity gate green and investigate its named label disagreements without tuning only to the benchmark.
2. Use `python3 scripts/ledger_review.py` to obtain two independent, evidenced reviews for each REVIEW_REQUIRED row; adjudicate disagreements outside the bot.
3. Verify the founder homepage at desktop, 390 px mobile, keyboard-only, zoom/reflow, success, validation-error, and scanner-error states.
4. Run the full project verification command from `AGENTS.md`.
5. Re-derive publication status from Git and GitHub. If a pull request exists, require green checks and preview evidence before deciding whether to merge; merge, release, and production deployment remain separate decisions.

## Source-of-truth commands

```bash
python3 scripts/ledger_status.py
python3 scripts/ledger_review.py summary
node tests/test_scanner_js.js
python3 scripts/current_state.py --check
git status --short --branch
git ls-remote origin refs/heads/feat/engagement-fixes refs/heads/main
```
"""


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    group = parser.add_mutually_exclusive_group()
    group.add_argument("--write", action="store_true")
    group.add_argument("--check", action="store_true")
    args = parser.parse_args(argv)
    try:
        text = render()
    except (OSError, RuntimeError, ValueError, json.JSONDecodeError) as error:
        print(f"current-state: {error}", file=sys.stderr)
        return 2
    if args.write:
        STATE_PATH.write_text(text, encoding="utf-8")
        print(f"current-state: wrote {STATE_PATH}")
        return 0
    if args.check:
        actual = STATE_PATH.read_text(encoding="utf-8")
        if actual != text:
            print(
                "current-state: STATE.md is stale; run "
                "python3 scripts/current_state.py --write",
                file=sys.stderr,
            )
            return 1
        print("current-state: STATE.md matches live repository measurements")
        return 0
    print(text, end="")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
