#!/usr/bin/env python3
"""
Regula Documentation Generator

Generates EU AI Act Annex IV documentation SCAFFOLDS and QMS (Quality Management
System) templates from project analysis.

Output is a starting point that requires human review and completion — it is
NOT complete compliance documentation and should not be presented as such.
"""

import argparse
import json
import os
import sys
from datetime import datetime, timezone
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))

from classify_risk import classify, RiskTier, is_ai_related, get_governance_contacts, check_ai_security
from log_event import log_event
from code_analysis import analyse_project_code


def scan_project(project_path: str) -> dict:
    """Scan a project directory for AI-related files and patterns."""
    project = Path(project_path).resolve()
    findings = {
        "ai_files": [],
        "model_files": [],
        "classifications": [],
        "highest_risk": RiskTier.NOT_AI,
    }

    risk_order = {
        RiskTier.NOT_AI: 0, RiskTier.MINIMAL_RISK: 1,
        RiskTier.LIMITED_RISK: 2, RiskTier.HIGH_RISK: 3, RiskTier.PROHIBITED: 4,
    }

    skip_dirs = {".git", "node_modules", "__pycache__", "venv", ".venv", "dist", "build", ".next"}
    code_extensions = {".py", ".js", ".ts", ".jsx", ".tsx", ".mjs", ".cjs"}
    model_extensions = {".onnx", ".pt", ".pth", ".pkl", ".joblib", ".h5", ".hdf5", ".safetensors", ".gguf", ".ggml"}

    for root, dirs, files in os.walk(project):
        dirs[:] = [d for d in dirs if d not in skip_dirs]
        for filename in files:
            filepath = Path(root) / filename
            rel_path = filepath.relative_to(project)

            if filepath.suffix in model_extensions:
                findings["model_files"].append(str(rel_path))
                continue

            if filepath.suffix in code_extensions:
                try:
                    content = filepath.read_text(encoding="utf-8", errors="ignore")
                except (PermissionError, OSError):
                    continue

                if is_ai_related(content):
                    findings["ai_files"].append(str(rel_path))
                    result = classify(content)
                    findings["classifications"].append({
                        "file": str(rel_path),
                        "tier": result.tier.value,
                        "indicators": result.indicators_matched,
                        "articles": result.applicable_articles,
                        "description": result.description,
                    })
                    if risk_order.get(result.tier, 0) > risk_order.get(findings["highest_risk"], 0):
                        findings["highest_risk"] = result.tier

    return findings


def _governance_section() -> str:
    """Generate the governance contacts section from policy."""
    contacts = get_governance_contacts()
    if not contacts:
        return """### Governance Contacts
_[TO BE COMPLETED — configure in regula-policy.yaml]_

- **AI Officer:** _[Name, Role, Email]_
- **DPO:** _[Name, Email]_
"""

    ai_officer = contacts.get("ai_officer", {})
    dpo = contacts.get("dpo", {})

    lines = ["### Governance Contacts\n"]

    if ai_officer and (ai_officer.get("name") or ai_officer.get("role")):
        name = ai_officer.get("name", "_[TO BE COMPLETED]_")
        role = ai_officer.get("role", "AI Officer")
        email = ai_officer.get("email", "_[TO BE COMPLETED]_")
        lines.append(f"- **AI Officer:** {name} ({role}) — {email}")
    else:
        lines.append("- **AI Officer:** _[TO BE COMPLETED — set governance.ai_officer in regula-policy.yaml]_")

    if dpo and (dpo.get("name") or dpo.get("email")):
        name = dpo.get("name", "_[TO BE COMPLETED]_")
        email = dpo.get("email", "_[TO BE COMPLETED]_")
        lines.append(f"- **DPO:** {name} — {email}")
    else:
        lines.append("- **DPO:** _[TO BE COMPLETED — set governance.dpo in regula-policy.yaml]_")

    lines.append("")
    return "\n".join(lines)


def generate_annex_iv(findings: dict, project_name: str, project_path: str) -> str:
    """Generate Annex IV compliant documentation."""
    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    highest = findings["highest_risk"]
    if isinstance(highest, RiskTier):
        highest = highest.value

    doc = f"""# Annex IV — Technical Documentation Scaffold

> **IMPORTANT:** This is an auto-generated scaffold, NOT complete compliance
> documentation. All sections marked _[TO BE COMPLETED]_ require human input.
> Risk indicators are pattern-based and may not reflect the actual risk
> classification under Article 6. This document must be reviewed by qualified
> personnel before being used as regulatory evidence.

## AI System: {project_name}

**Generated by:** Regula v1.1.0
**Date:** {now}
**Overall Risk Classification:** {highest.upper().replace('_', '-')}

---

## 0. Governance

{_governance_section()}
---

## 1. General Description

### 1.1 System Identity
- **System name:** {project_name}
- **Project path:** {project_path}
- **Documentation date:** {now}
- **Classification:** {highest.upper().replace('_', '-')}

### 1.2 AI Components Detected

| File | Risk Tier | Indicators | Applicable Articles |
|------|-----------|------------|---------------------|
"""

    for c in findings["classifications"]:
        articles = ", ".join(c["articles"]) if c["articles"] else "N/A"
        indicators = ", ".join(c["indicators"]) if c["indicators"] else "N/A"
        doc += f"| {c['file']} | {c['tier'].upper().replace('_', '-')} | {indicators} | {articles} |\n"

    if not findings["classifications"]:
        doc += "| _No AI components detected_ | — | — | — |\n"

    if findings["model_files"]:
        doc += "\n### 1.3 Model Files\n\n"
        for mf in findings["model_files"]:
            doc += f"- `{mf}`\n"

    # Auto-populate sections 2-4 from code analysis
    analysis = analyse_project_code(project_path)

    doc += "\n---\n\n## 2. Detailed Description of Elements and Development Process\n\n"

    # 2.1 Development Methods
    doc += "### 2.1 Development Methods\n_[TO BE COMPLETED BY DEVELOPMENT TEAM]_\n\n"

    # 2.2 Data Requirements — auto-populated from detected sources
    doc += "### 2.2 Data Requirements\n"
    if analysis["data_sources"]:
        doc += "_[AUTO-DETECTED — VERIFY]_ The following data sources were detected:\n\n"
        for ds in analysis["data_sources"]:
            doc += f"- {ds}\n"
        doc += "\n_Review data governance requirements per Article 10._\n\n"
    else:
        doc += "_[TO BE COMPLETED BY DEVELOPMENT TEAM]_\n\n"

    # 2.3 Model Architecture — auto-populated from detected imports
    doc += "### 2.3 Model Architecture\n"
    if analysis["architectures"]:
        doc += "_[AUTO-DETECTED — VERIFY]_ The following AI frameworks/architectures were detected:\n\n"
        for arch in analysis["architectures"]:
            doc += f"- {arch}\n"
        doc += "\n_Document model parameters, training methodology, and performance characteristics._\n\n"
    else:
        doc += "_[TO BE COMPLETED BY DEVELOPMENT TEAM]_\n\n"

    doc += "---\n\n## 3. Monitoring, Functioning, and Control\n\n"

    # 3.1 Performance Metrics
    doc += "### 3.1 Performance Metrics\n_[TO BE COMPLETED BY DEVELOPMENT TEAM]_\n\n"

    # 3.2 Known Limitations
    doc += "### 3.2 Known Limitations\n_[TO BE COMPLETED BY DEVELOPMENT TEAM]_\n\n"

    # 3.3 Human Oversight — auto-populated from detected patterns
    doc += "### 3.3 Human Oversight\n"
    if analysis["oversight"]:
        doc += "_[AUTO-DETECTED — VERIFY]_ The following oversight mechanisms were detected:\n\n"
        for o in analysis["oversight"]:
            doc += f"- {o}\n"
        doc += "\n_Verify these mechanisms meet Article 14 requirements._\n\n"
    else:
        doc += "_No human oversight patterns detected._ Review Article 14 requirements.\n\n"

    # 3.4 Logging — auto-populated from detected patterns
    doc += "### 3.4 Logging Infrastructure\n"
    if analysis["logging"]:
        doc += "_[AUTO-DETECTED — VERIFY]_ The following logging mechanisms were detected:\n\n"
        for lg in analysis["logging"]:
            doc += f"- {lg}\n"
        doc += "\n_Verify logging meets Article 12 record-keeping requirements._\n\n"
    else:
        doc += "_No logging infrastructure detected._ Article 12 requires automatic recording of events.\n\n"

    # 4. Risk Register — auto-populated from security findings
    doc += "---\n\n## 4. Risk Management System (Article 9)\n\n"
    security_findings = []
    for c in findings["classifications"]:
        filepath = Path(project_path) / c["file"]
        if filepath.exists():
            try:
                text = filepath.read_text(encoding="utf-8", errors="ignore")
                sf = check_ai_security(text)
                for f in sf:
                    f["file"] = c["file"]
                security_findings.extend(sf)
            except OSError:
                pass

    if security_findings or findings["classifications"]:
        doc += "### Risk Register\n\n"
        doc += "_[AUTO-DETECTED — VERIFY]_\n\n"
        doc += "| Risk ID | File | Description | OWASP Mapping | Severity | Mitigation |\n"
        doc += "|---------|------|-------------|---------------|----------|------------|\n"
        rid = 1
        for c in findings["classifications"]:
            tier = c["tier"].upper().replace("_", "-")
            doc += f"| R{rid:03d} | {c['file']} | {c['description']} ({tier}) | — | {tier} | _[TO BE COMPLETED]_ |\n"
            rid += 1
        for sf in security_findings:
            doc += f"| R{rid:03d} | {sf['file']} | {sf['description']} | {sf['owasp']} | {sf['severity'].upper()} | {sf['remediation'][:60]} |\n"
            rid += 1
        doc += "\n"
    else:
        doc += "_[TO BE COMPLETED BY DEVELOPMENT TEAM]_\n\n"

    doc += "---\n\n## 5. Compliance Requirements\n\n"


    if highest in ("high_risk", "prohibited"):
        doc += """The following EU AI Act articles apply to this system:

| Article | Requirement | Status |
|---------|-------------|--------|
| Article 9 | Risk management system | [ ] Not started |
| Article 10 | Data governance | [ ] Not started |
| Article 11 | Technical documentation | [ ] In progress (this document) |
| Article 12 | Record-keeping | [ ] Not started |
| Article 13 | Transparency | [ ] Not started |
| Article 14 | Human oversight | [ ] Not started |
| Article 15 | Accuracy, robustness, cybersecurity | [ ] Not started |

**Compliance deadline:** 2 August 2026
"""
    elif highest == "limited_risk":
        doc += """**Article 50 (Transparency) applies.**

| Requirement | Status |
|-------------|--------|
| Users informed of AI interaction | [ ] Not started |
| AI-generated content labelled | [ ] Not started |
"""
    else:
        doc += "No specific EU AI Act compliance requirements identified for this risk tier.\n"

    doc += f"""
---

## 6. Audit Trail Reference

Regula audit events for this system are stored in `~/.regula/audit/`.
Verify chain integrity: `python3 scripts/log_event.py verify`

---

## 7. EU Declaration of Conformity
_[TO BE COMPLETED BEFORE MARKET PLACEMENT]_

---

_Generated by Regula v1.1.0 — AI Governance Risk Indication_
_Template based on EU AI Act (Regulation 2024/1689) Annex IV_
_Generated on {now}_
"""

    return doc


def generate_qms_scaffold(findings: dict, project_name: str, project_path: str) -> str:
    """Generate a Quality Management System scaffold per Article 17.

    Article 17 requires providers of high-risk AI systems to put in place a
    quality management system. This scaffold covers the required elements.
    """
    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    highest = findings["highest_risk"]
    if isinstance(highest, RiskTier):
        highest = highest.value

    doc = f"""# Quality Management System Scaffold — Article 17

> **IMPORTANT:** This is an auto-generated scaffold. All sections require
> human completion and review by qualified personnel. A QMS cannot be
> auto-generated — this provides the structure, not the substance.

## AI System: {project_name}

**Generated by:** Regula v1.1.0
**Date:** {now}

---

## 0. Governance and Accountability

{_governance_section()}
**Accountability structure:**

| Role | Responsibility | Person |
|------|---------------|--------|
| AI Officer | Overall AI governance accountability | _[TO BE COMPLETED]_ |
| DPO | Data protection oversight | _[TO BE COMPLETED]_ |
| Technical Lead | System design and implementation | _[TO BE COMPLETED]_ |
| Risk Owner | Risk assessment and monitoring | _[TO BE COMPLETED]_ |

---

## 1. Strategy and Compliance Objectives (Art. 17(1)(a))

_[TO BE COMPLETED]_

- Regulatory framework: EU AI Act (Regulation 2024/1689)
- Risk classification: {highest.upper().replace('_', '-')}
- Compliance target date: _[TO BE COMPLETED]_

---

## 2. Techniques, Procedures, and Actions for Design and Development (Art. 17(1)(b))

_[TO BE COMPLETED]_

### 2.1 Development Lifecycle
- [ ] Requirements specification
- [ ] Design documentation
- [ ] Implementation standards
- [ ] Code review procedures
- [ ] Testing methodology

### 2.2 Data Management (Article 10)
- [ ] Training data documentation
- [ ] Data quality assessment
- [ ] Bias detection procedures
- [ ] Data governance framework

---

## 3. Techniques, Procedures, and Actions for Testing and Validation (Art. 17(1)(c))

_[TO BE COMPLETED]_

- [ ] Performance testing criteria
- [ ] Bias and fairness testing
- [ ] Robustness testing
- [ ] Security testing
- [ ] Validation against intended purpose

---

## 4. Technical Specifications and Standards (Art. 17(1)(d))

_[TO BE COMPLETED]_

| Standard | Status | Notes |
|----------|--------|-------|
| ISO 42001 (AI Management System) | [ ] Not started | |
| prEN 18286 (QMS for AI) | [ ] Awaiting publication | Public enquiry closes Oct 2026 |
| ISO 23894 (AI Risk Management) | [ ] Not started | |

---

## 5. Systems and Procedures for Data Management (Art. 17(1)(e))

_[TO BE COMPLETED]_

- [ ] Data inventory
- [ ] Data lineage tracking
- [ ] Data quality metrics
- [ ] Data retention policy

---

## 6. Risk Management System (Art. 17(1)(f), Art. 9)

_[TO BE COMPLETED]_

### 6.1 Known Risks

| Risk | Likelihood | Impact | Mitigation | Owner |
|------|-----------|--------|------------|-------|
| _[TO BE COMPLETED]_ | | | | |

### 6.2 Risk Monitoring
- [ ] Monitoring frequency defined
- [ ] Risk escalation procedures
- [ ] Incident response plan

---

## 7. Post-Market Monitoring (Art. 17(1)(g), Art. 72)

_[TO BE COMPLETED]_

- [ ] Monitoring plan documented
- [ ] Feedback collection mechanism
- [ ] Performance degradation detection
- [ ] Incident reporting procedures

---

## 8. Record-Keeping (Art. 17(1)(h), Art. 12)

- Regula audit trail: `~/.regula/audit/`
- Chain integrity verification: `regula audit verify`
- [ ] Additional logging requirements identified
- [ ] Log retention policy: _[TO BE COMPLETED]_ years

---

## 9. Corrective Actions (Art. 17(1)(i))

_[TO BE COMPLETED]_

- [ ] Non-conformity identification process
- [ ] Root cause analysis procedures
- [ ] Corrective action implementation
- [ ] Effectiveness verification

---

## 10. Communication with Authorities (Art. 17(1)(j))

_[TO BE COMPLETED]_

- National competent authority: _[TO BE COMPLETED]_
- Notification procedures: _[TO BE COMPLETED]_
- Serious incident reporting: _[TO BE COMPLETED]_

---

## 11. Human Oversight (Art. 14)

_[TO BE COMPLETED]_

- [ ] Human oversight mechanism defined
- [ ] Override capability documented
- [ ] Operator training programme
- [ ] Decision escalation criteria

---

## 12. Transparency (Art. 13)

_[TO BE COMPLETED]_

- [ ] Instructions for use documented
- [ ] Capabilities and limitations described
- [ ] Performance characteristics disclosed
- [ ] Intended purpose clearly defined

---

## Review Schedule

| Review | Frequency | Next Due | Responsible |
|--------|-----------|----------|-------------|
| Full QMS review | Annual | _[TO BE COMPLETED]_ | AI Officer |
| Risk assessment | Quarterly | _[TO BE COMPLETED]_ | Risk Owner |
| Audit trail verification | Monthly | _[TO BE COMPLETED]_ | Technical Lead |
| Incident review | Per incident | — | AI Officer |

---

_Generated by Regula v1.1.0 — AI Governance Risk Indication_
_Template based on EU AI Act (Regulation 2024/1689) Article 17_
_Generated on {now}_
"""

    return doc


def generate_model_card(findings: dict, project_name: str, project_path: str) -> str:
    """Generate a HuggingFace-compatible model card.

    See https://huggingface.co/docs/hub/model-cards for format.
    """
    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    highest = findings["highest_risk"]
    if isinstance(highest, RiskTier):
        highest = highest.value

    analysis = analyse_project_code(project_path)

    doc = f"""---
license: _[TO BE COMPLETED]_
tags:
  - regula-scanned
  - eu-ai-act
---

# Model Card: {project_name}

> _[AUTO-DETECTED — VERIFY]_ This model card was auto-generated by Regula v1.1.0.
> All sections require human review before publication.

## Model Details

### Model Description

- **Developed by:** _[TO BE COMPLETED]_
- **Model type:** {', '.join(analysis['architectures']) if analysis['architectures'] else '_[TO BE COMPLETED]_'}
- **Language(s):** _[TO BE COMPLETED]_
- **License:** _[TO BE COMPLETED]_
- **EU AI Act Risk Classification:** {highest.upper().replace('_', '-')}

### Model Sources

- **Repository:** {project_path}
- **Documentation:** _[TO BE COMPLETED]_

## Uses

### Direct Use
_[TO BE COMPLETED]_

### Out-of-Scope Use
_[TO BE COMPLETED]_

## Training Details

### Training Data
"""
    if analysis["data_sources"]:
        doc += "_[AUTO-DETECTED — VERIFY]_ Detected data sources:\n\n"
        for ds in analysis["data_sources"]:
            doc += f"- {ds}\n"
    else:
        doc += "_[TO BE COMPLETED]_\n"

    doc += """
### Training Procedure
_[TO BE COMPLETED]_

## Evaluation

### Metrics
_[TO BE COMPLETED]_

### Results
_[TO BE COMPLETED]_

## Environmental Impact
_[TO BE COMPLETED]_

## Technical Specifications
_[TO BE COMPLETED]_

## EU AI Act Compliance

"""
    if highest in ("high_risk", "prohibited"):
        doc += f"**Risk tier:** {highest.upper().replace('_', '-')}\n\n"
        doc += "Articles 9-15 apply. See Annex IV documentation for full compliance status.\n\n"
        if analysis["oversight"]:
            doc += "**Human oversight mechanisms detected:**\n\n"
            for o in analysis["oversight"]:
                doc += f"- _[AUTO-DETECTED — VERIFY]_ {o}\n"
        else:
            doc += "**No human oversight mechanisms detected.** Article 14 compliance required.\n"
    elif highest == "limited_risk":
        doc += "**Risk tier:** LIMITED-RISK\n\nArticle 50 transparency requirements apply.\n"
    else:
        doc += "**Risk tier:** MINIMAL-RISK\n\nNo specific EU AI Act requirements.\n"

    doc += f"""
---

_Generated by Regula v1.1.0 on {now}_
"""
    return doc


def main():
    parser = argparse.ArgumentParser(description="Generate Annex IV technical documentation and QMS scaffolds")
    parser.add_argument("--project", "-p", default=".", help="Project directory to scan")
    parser.add_argument("--output", "-o", default="docs", help="Output directory")
    parser.add_argument("--name", "-n", help="Project name (defaults to directory name)")
    parser.add_argument("--format", choices=["markdown", "json"], default="markdown")
    parser.add_argument("--qms", action="store_true", help="Also generate QMS scaffold (Article 17)")
    parser.add_argument("--all", action="store_true", help="Generate all documentation types")
    args = parser.parse_args()

    project_path = str(Path(args.project).resolve())
    project_name = args.name or Path(project_path).name

    print(f"Scanning {project_path}...")
    findings = scan_project(project_path)

    ai_count = len(findings["ai_files"])
    model_count = len(findings["model_files"])
    highest = findings["highest_risk"]
    if isinstance(highest, RiskTier):
        highest = highest.value
    print(f"Found {ai_count} AI-related files, {model_count} model files")
    print(f"Highest risk tier: {highest.upper().replace('_', '-')}")

    output_dir = Path(args.output)
    output_dir.mkdir(parents=True, exist_ok=True)

    if args.format == "json":
        output_file = output_dir / f"{project_name}_annex_iv.json"
        json_findings = dict(findings)
        json_findings["highest_risk"] = highest
        output_file.write_text(json.dumps(json_findings, indent=2, default=str), encoding="utf-8")
        print(f"Documentation written to {output_file}")
    else:
        # Annex IV
        output_file = output_dir / f"{project_name}_annex_iv.md"
        doc = generate_annex_iv(findings, project_name, project_path)
        output_file.write_text(doc, encoding="utf-8")
        print(f"Annex IV documentation written to {output_file}")

        # QMS scaffold
        if args.qms or getattr(args, "all", False):
            qms_file = output_dir / f"{project_name}_qms.md"
            qms_doc = generate_qms_scaffold(findings, project_name, project_path)
            qms_file.write_text(qms_doc, encoding="utf-8")
            print(f"QMS scaffold written to {qms_file}")

    try:
        log_event("documentation_generated", {
            "project": project_name, "highest_risk": highest,
            "ai_files": ai_count, "model_files": model_count,
            "types": ["annex_iv"] + (["qms"] if args.qms or getattr(args, "all", False) else []),
        })
    except (OSError,):
        pass


if __name__ == "__main__":
    main()
