#!/usr/bin/env python3
"""
Regula Documentation Generator
Generates EU AI Act Annex IV compliant technical documentation.
"""

import argparse
import json
import os
import sys
from datetime import datetime, timezone
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))

from classify_risk import classify, RiskTier, is_ai_related
from log_event import log_event


def scan_project(project_path: str) -> dict:
    """Scan a project directory for AI-related files and patterns."""
    project = Path(project_path).resolve()
    findings = {
        "ai_files": [],
        "model_files": [],
        "classifications": [],
        "highest_risk": RiskTier.NOT_AI,
    }

    risk_order = {
        RiskTier.NOT_AI: 0, RiskTier.MINIMAL_RISK: 1,
        RiskTier.LIMITED_RISK: 2, RiskTier.HIGH_RISK: 3, RiskTier.PROHIBITED: 4,
    }

    skip_dirs = {".git", "node_modules", "__pycache__", "venv", ".venv", "dist", "build", ".next"}
    code_extensions = {".py", ".js", ".ts", ".jsx", ".tsx", ".mjs", ".cjs"}
    model_extensions = {".onnx", ".pt", ".pth", ".pkl", ".joblib", ".h5", ".hdf5", ".safetensors", ".gguf", ".ggml"}

    for root, dirs, files in os.walk(project):
        dirs[:] = [d for d in dirs if d not in skip_dirs]
        for filename in files:
            filepath = Path(root) / filename
            rel_path = filepath.relative_to(project)

            if filepath.suffix in model_extensions:
                findings["model_files"].append(str(rel_path))
                continue

            if filepath.suffix in code_extensions:
                try:
                    content = filepath.read_text(encoding="utf-8", errors="ignore")
                except (PermissionError, OSError):
                    continue

                if is_ai_related(content):
                    findings["ai_files"].append(str(rel_path))
                    result = classify(content)
                    findings["classifications"].append({
                        "file": str(rel_path),
                        "tier": result.tier.value,
                        "indicators": result.indicators_matched,
                        "articles": result.applicable_articles,
                        "description": result.description,
                    })
                    if risk_order.get(result.tier, 0) > risk_order.get(findings["highest_risk"], 0):
                        findings["highest_risk"] = result.tier

    return findings


def generate_annex_iv(findings: dict, project_name: str, project_path: str) -> str:
    """Generate Annex IV compliant documentation."""
    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    highest = findings["highest_risk"]
    if isinstance(highest, RiskTier):
        highest = highest.value

    doc = f"""# Annex IV — Technical Documentation

## AI System: {project_name}

**Generated by:** Regula v1.0.0
**Date:** {now}
**Overall Risk Classification:** {highest.upper().replace('_', '-')}

---

## 1. General Description

### 1.1 System Identity
- **System name:** {project_name}
- **Project path:** {project_path}
- **Documentation date:** {now}
- **Classification:** {highest.upper().replace('_', '-')}

### 1.2 AI Components Detected

| File | Risk Tier | Indicators | Applicable Articles |
|------|-----------|------------|---------------------|
"""

    for c in findings["classifications"]:
        articles = ", ".join(c["articles"]) if c["articles"] else "N/A"
        indicators = ", ".join(c["indicators"]) if c["indicators"] else "N/A"
        doc += f"| {c['file']} | {c['tier'].upper().replace('_', '-')} | {indicators} | {articles} |\n"

    if not findings["classifications"]:
        doc += "| _No AI components detected_ | — | — | — |\n"

    if findings["model_files"]:
        doc += "\n### 1.3 Model Files\n\n"
        for mf in findings["model_files"]:
            doc += f"- `{mf}`\n"

    doc += """
---

## 2. Detailed Description of Elements and Development Process

### 2.1 Development Methods
_[TO BE COMPLETED BY DEVELOPMENT TEAM]_

### 2.2 Data Requirements
_[TO BE COMPLETED BY DEVELOPMENT TEAM]_

### 2.3 Model Architecture
_[TO BE COMPLETED BY DEVELOPMENT TEAM]_

---

## 3. Monitoring, Functioning, and Control

### 3.1 Performance Metrics
_[TO BE COMPLETED BY DEVELOPMENT TEAM]_

### 3.2 Known Limitations
_[TO BE COMPLETED BY DEVELOPMENT TEAM]_

### 3.3 Human Oversight
_[TO BE COMPLETED BY DEVELOPMENT TEAM]_

---

## 4. Risk Management System (Article 9)
_[TO BE COMPLETED BY DEVELOPMENT TEAM]_

---

## 5. Compliance Requirements

"""

    if highest in ("high_risk", "prohibited"):
        doc += """The following EU AI Act articles apply to this system:

| Article | Requirement | Status |
|---------|-------------|--------|
| Article 9 | Risk management system | [ ] Not started |
| Article 10 | Data governance | [ ] Not started |
| Article 11 | Technical documentation | [ ] In progress (this document) |
| Article 12 | Record-keeping | [ ] Not started |
| Article 13 | Transparency | [ ] Not started |
| Article 14 | Human oversight | [ ] Not started |
| Article 15 | Accuracy, robustness, cybersecurity | [ ] Not started |

**Compliance deadline:** 2 August 2026
"""
    elif highest == "limited_risk":
        doc += """**Article 50 (Transparency) applies.**

| Requirement | Status |
|-------------|--------|
| Users informed of AI interaction | [ ] Not started |
| AI-generated content labelled | [ ] Not started |
"""
    else:
        doc += "No specific EU AI Act compliance requirements identified for this risk tier.\n"

    doc += f"""
---

## 6. Audit Trail Reference

Regula audit events for this system are stored in `~/.regula/audit/`.
Verify chain integrity: `python3 scripts/log_event.py verify`

---

## 7. EU Declaration of Conformity
_[TO BE COMPLETED BEFORE MARKET PLACEMENT]_

---

_Generated by Regula v1.0.0 — AI Governance Enforcement_
_Template based on EU AI Act (Regulation 2024/1689) Annex IV_
_Generated on {now}_
"""

    return doc


def main():
    parser = argparse.ArgumentParser(description="Generate Annex IV technical documentation")
    parser.add_argument("--project", "-p", default=".", help="Project directory to scan")
    parser.add_argument("--output", "-o", default="docs", help="Output directory")
    parser.add_argument("--name", "-n", help="Project name (defaults to directory name)")
    parser.add_argument("--format", choices=["markdown", "json"], default="markdown")
    args = parser.parse_args()

    project_path = str(Path(args.project).resolve())
    project_name = args.name or Path(project_path).name

    print(f"Scanning {project_path}...")
    findings = scan_project(project_path)

    ai_count = len(findings["ai_files"])
    model_count = len(findings["model_files"])
    highest = findings["highest_risk"]
    if isinstance(highest, RiskTier):
        highest = highest.value
    print(f"Found {ai_count} AI-related files, {model_count} model files")
    print(f"Highest risk tier: {highest.upper().replace('_', '-')}")

    output_dir = Path(args.output)
    output_dir.mkdir(parents=True, exist_ok=True)

    if args.format == "json":
        output_file = output_dir / f"{project_name}_annex_iv.json"
        json_findings = dict(findings)
        json_findings["highest_risk"] = highest
        output_file.write_text(json.dumps(json_findings, indent=2, default=str), encoding="utf-8")
    else:
        output_file = output_dir / f"{project_name}_annex_iv.md"
        doc = generate_annex_iv(findings, project_name, project_path)
        output_file.write_text(doc, encoding="utf-8")

    print(f"Documentation written to {output_file}")

    try:
        log_event("documentation_generated", {
            "project": project_name, "highest_risk": highest,
            "ai_files": ai_count, "model_files": model_count,
        })
    except Exception:
        pass


if __name__ == "__main__":
    main()
