#!/usr/bin/env python3
"""
Regula PDF Export

Renders Annex IV documentation to PDF using weasyprint (optional).
Falls back to HTML with print-to-PDF instructions when weasyprint is absent.

Install weasyprint: pip install regula[pdf]
"""

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))

# CSS for Annex IV PDF output — clean, print-ready
_PDF_CSS = """
@page {
    size: A4;
    margin: 2.5cm 2cm;
    @top-center { content: "EU AI Act — Technical Documentation (Annex IV)"; font-size: 9pt; color: #666; }
    @bottom-right { content: "Page " counter(page) " of " counter(pages); font-size: 9pt; color: #666; }
}
body { font-family: 'Helvetica Neue', Arial, sans-serif; font-size: 10pt; line-height: 1.5; color: #1a1a1a; }
h1 { font-size: 18pt; color: #003087; border-bottom: 2px solid #003087; padding-bottom: 8pt; }
h2 { font-size: 13pt; color: #003087; margin-top: 18pt; border-bottom: 1px solid #ccc; }
h3 { font-size: 11pt; color: #444; }
table { width: 100%; border-collapse: collapse; margin: 12pt 0; font-size: 9pt; }
th { background: #003087; color: white; padding: 6pt 8pt; text-align: left; }
td { padding: 5pt 8pt; border-bottom: 1px solid #e0e0e0; }
tr:nth-child(even) td { background: #f7f9ff; }
.risk-prohibited { color: #c0392b; font-weight: bold; }
.risk-high { color: #e67e22; font-weight: bold; }
.risk-limited { color: #2980b9; }
.risk-minimal { color: #27ae60; }
.placeholder { color: #999; font-style: italic; }
.auto-detected { color: #666; font-size: 8.5pt; }
blockquote { border-left: 3px solid #003087; margin: 8pt 0 8pt 12pt; padding-left: 8pt; color: #555; }
code { background: #f0f0f0; padding: 1pt 3pt; font-size: 8.5pt; border-radius: 2pt; }
pre { background: #f5f5f5; padding: 8pt; font-size: 8pt; overflow: auto; }
"""

_HTML_WRAPPER = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>{title}</title>
<style>
{css}
</style>
</head>
<body>
{body}
<div style="margin-top:40pt; border-top:1px solid #ccc; padding-top:8pt; font-size:8pt; color:#999;">
Generated by Regula v1.2.0 — This is a scaffold. All sections marked [TO BE COMPLETED] require human review.
</div>
</body>
</html>"""


def _markdown_to_html_body(md_content: str) -> str:
    """Convert markdown to HTML body (minimal, stdlib-only)."""
    import re
    lines = md_content.split("\n")
    html_lines = []
    in_table = False
    in_code = False

    for line in lines:
        # Fenced code blocks
        if line.strip().startswith("```"):
            if in_code:
                html_lines.append("</code></pre>")
                in_code = False
            else:
                html_lines.append("<pre><code>")
                in_code = True
            continue
        if in_code:
            from html import escape
            html_lines.append(escape(line))
            continue

        # Tables
        if "|" in line and line.strip().startswith("|"):
            if not in_table:
                html_lines.append('<table>')
                in_table = True
            cells = [c.strip() for c in line.strip().strip("|").split("|")]
            if all(re.match(r'^-+$', c) for c in cells):
                continue  # Skip separator row
            if not any("<td>" in l for l in html_lines[-5:]):
                tag = "th"
            else:
                tag = "td"
            row = "".join(f"<{tag}>{c}</{tag}>" for c in cells)
            html_lines.append(f"<tr>{row}</tr>")
            continue
        elif in_table:
            html_lines.append("</table>")
            in_table = False

        # Headings
        m = re.match(r'^(#{1,6})\s+(.*)', line)
        if m:
            level = len(m.group(1))
            text = m.group(2)
            html_lines.append(f"<h{level}>{text}</h{level}>")
            continue

        # Horizontal rules
        if re.match(r'^-{3,}$', line.strip()):
            html_lines.append("<hr>")
            continue

        # Blank lines → paragraph break
        if not line.strip():
            html_lines.append("<br>")
            continue

        # Inline: bold, italic, code
        text = line
        from html import escape
        text = escape(text)
        text = re.sub(r'\*\*(.+?)\*\*', r'<strong>\1</strong>', text)
        text = re.sub(r'_(.+?)_', r'<em>\1</em>', text)
        text = re.sub(r'`(.+?)`', r'<code>\1</code>', text)
        text = re.sub(r'(\[TO BE COMPLETED[^\]]*\])', r'<span class="placeholder">\1</span>', text)
        text = re.sub(r'(AUTO-DETECTED.*?VERIFY)', r'<span class="auto-detected">\1</span>', text)
        html_lines.append(f"<p>{text}</p>")

    if in_table:
        html_lines.append("</table>")
    if in_code:
        html_lines.append("</code></pre>")

    return "\n".join(html_lines)


def generate_annex_iv_html(project_path: str, system_name: str = "") -> str:
    """Generate an HTML string for the Annex IV document.

    Calls generate_documentation.generate_annex_iv() for the markdown,
    then wraps it in the PDF-ready HTML template.
    """
    from generate_documentation import generate_annex_iv, scan_project

    scan = scan_project(project_path)
    name = system_name or Path(project_path).name
    md_content = generate_annex_iv(scan, name, project_path)
    body = _markdown_to_html_body(md_content)
    title = f"Annex IV — {name}"
    return _HTML_WRAPPER.format(title=title, css=_PDF_CSS, body=body)


def render_to_pdf(html_content: str, fallback_to_html: bool = True) -> bytes:
    """Render HTML to PDF bytes using weasyprint.

    Parameters
    ----------
    html_content : str
        Complete HTML document to render.
    fallback_to_html : bool
        If True and weasyprint is not installed, return HTML bytes instead.
        If False and weasyprint is not installed, raise ImportError.

    Returns
    -------
    bytes
        PDF bytes (or HTML bytes in fallback mode).

    Raises
    ------
    ImportError
        If weasyprint is not installed and fallback_to_html is False.
    """
    try:
        import weasyprint
        return weasyprint.HTML(string=html_content).write_pdf()
    except (ImportError, TypeError):
        if fallback_to_html:
            return html_content.encode("utf-8")
        raise ImportError(
            "weasyprint is not installed. Install it with: pip install 'regula[pdf]'\n"
            "Or open the HTML file in a browser and use File \u2192 Print \u2192 Save as PDF."
        )
