#!/usr/bin/env python3
# regula-ignore
"""
Regula Transparency Disclosure Generator (Article 50)

Generates EU AI Act transparency notices for:
- Article 50(1): Chatbots and AI interaction disclosure
- Article 50(2): Synthetic content labelling (text, image, audio, video)
- Article 50(3): Emotion recognition system disclosure
- Article 50(4): Deep fake labelling

Output is copy-paste-ready text for integration into AI applications.
"""
import sys
from datetime import datetime, timezone
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))


# ---------------------------------------------------------------------------
# Disclosure templates per Article 50 subsection
# ---------------------------------------------------------------------------

DISCLOSURES = {
    "chatbot": {
        "article": "Article 50(1)",
        "requirement": "Providers shall ensure that AI systems intended to interact directly with natural persons are designed and developed in such a way that the natural persons concerned are informed that they are interacting with an AI system, unless this is obvious from the point of view of a natural person who is reasonably well-informed.",
        "template_text": (
            "You are interacting with an AI system. This system is powered by "
            "artificial intelligence and is not a human. A human representative "
            "is available upon request."
        ),
        "template_html": (
            '<div class="ai-disclosure" role="alert" aria-label="AI system disclosure">'
            '<p>You are interacting with an AI system. This system is powered by '
            'artificial intelligence and is not a human. A human representative '
            'is available upon request.</p></div>'
        ),
        "template_code_python": (
            "# Article 50(1) — AI interaction disclosure\n"
            "AI_DISCLOSURE = (\n"
            '    "You are interacting with an AI system. "\n'
            '    "This system is powered by artificial intelligence "\n'
            '    "and is not a human. A human representative is "\n'
            '    "available upon request."\n'
            ")\n\n"
            "def get_ai_disclosure() -> str:\n"
            '    """Return the AI interaction disclosure notice (Article 50(1))."""\n'
            "    return AI_DISCLOSURE\n"
        ),
        "placement": "Must be displayed before or at the start of the interaction.",
        "exceptions": "Not required when obvious to a reasonable person (e.g., voice assistants with clearly synthetic voice).",
    },
    "synthetic_text": {
        "article": "Article 50(2)",
        "requirement": "Providers of AI systems that generate synthetic content shall ensure that the output is marked in a machine-readable format and detectable as artificially generated or manipulated.",
        "template_text": (
            "This content was generated by an AI system and may not reflect "
            "human authorship. AI-generated content should be independently "
            "verified before reliance."
        ),
        "template_html": (
            '<div class="ai-generated-content" data-ai-generated="true" '
            'data-generator="{system_name}" data-timestamp="{timestamp}">'
            '<p class="ai-label">AI-generated content</p></div>'
        ),
        "template_code_python": (
            "# Article 50(2) — Synthetic content labelling\n"
            "def label_ai_content(content: str, system_name: str) -> dict:\n"
            '    """Label AI-generated content per Article 50(2)."""\n'
            "    return {\n"
            '        "content": content,\n'
            '        "metadata": {\n'
            '            "ai_generated": True,\n'
            '            "generator": system_name,\n'
            '            "timestamp": datetime.now(timezone.utc).isoformat(),\n'
            '            "eu_ai_act_article": "50(2)",\n'
            "        }\n"
            "    }\n"
        ),
        "placement": "Metadata must be embedded in the content itself (machine-readable).",
        "exceptions": "AI systems performing assistive functions (e.g., spell-check) are exempt if they do not substantially alter the input.",
    },
    "emotion_recognition": {
        "article": "Article 50(3)",
        "requirement": "Deployers of emotion recognition systems or biometric categorisation systems shall inform natural persons exposed thereto of the operation of the system.",
        "template_text": (
            "This system uses emotion recognition technology to analyse "
            "facial expressions, voice patterns, or other biometric signals. "
            "Your emotional state may be inferred during this interaction. "
            "You have the right to object to this processing."
        ),
        "template_html": (
            '<div class="emotion-recognition-notice" role="alert">'
            '<p><strong>Emotion Recognition Notice:</strong> This system analyses '
            'biometric signals to infer emotional states. You have the right to '
            'object to this processing.</p></div>'
        ),
        "template_code_python": (
            "# Article 50(3) — Emotion recognition disclosure\n"
            "EMOTION_NOTICE = (\n"
            '    "This system uses emotion recognition technology to analyse "\n'
            '    "facial expressions, voice patterns, or other biometric signals. "\n'
            '    "Your emotional state may be inferred during this interaction. "\n'
            '    "You have the right to object to this processing."\n'
            ")\n"
        ),
        "placement": "Must be provided before the system processes biometric data.",
        "exceptions": "Exempt when used for medical or safety purposes (e.g., driver fatigue detection).",
    },
    "deepfake": {
        "article": "Article 50(4)",
        "requirement": "Deployers of AI systems that generate or manipulate image, audio, or video content constituting a deep fake shall disclose that the content has been artificially generated or manipulated.",
        "template_text": (
            "This content has been artificially generated or manipulated "
            "using AI technology. It does not depict real events."
        ),
        "template_html": (
            '<div class="deepfake-label" role="alert" data-synthetic="true">'
            '<p><strong>AI-Generated Content:</strong> This media has been '
            'artificially generated or manipulated using AI technology.</p></div>'
        ),
        "template_code_python": (
            "# Article 50(4) — Deep fake labelling\n"
            "def label_deepfake(media_path: str, media_type: str) -> dict:\n"
            '    """Label deep fake content per Article 50(4)."""\n'
            "    return {\n"
            '        "media": media_path,\n'
            '        "type": media_type,  # "image", "audio", "video"\n'
            '        "synthetic": True,\n'
            '        "label": "This content has been artificially generated "\n'
            '                 "or manipulated using AI technology.",\n'
            '        "eu_ai_act_article": "50(4)",\n'
            "    }\n"
        ),
        "placement": "Must accompany the content when published or distributed.",
        "exceptions": "Exempt when content is part of an obviously artistic, satirical, or fictional work, provided it does not constitute a deep fake.",
    },
}


# ---------------------------------------------------------------------------
# Generator functions
# ---------------------------------------------------------------------------

def generate_disclosure(
    disclosure_type: str,
    output_format: str = "text",
    system_name: str = "AI System",
) -> dict:
    """Generate a transparency disclosure for a given type.

    Args:
        disclosure_type: One of "chatbot", "synthetic_text", "emotion_recognition", "deepfake", "all"
        output_format: "text", "html", "code", or "all"
        system_name: Name of the AI system for templates.

    Returns:
        Dict with article, requirement, and generated templates.
    """
    if disclosure_type == "all":
        return {
            dtype: generate_disclosure(dtype, output_format, system_name)
            for dtype in DISCLOSURES
        }

    if disclosure_type not in DISCLOSURES:
        return {"error": f"Unknown type: {disclosure_type}. Options: {', '.join(DISCLOSURES.keys())}, all"}

    d = DISCLOSURES[disclosure_type]
    result = {
        "type": disclosure_type,
        "article": d["article"],
        "requirement": d["requirement"],
        "placement": d["placement"],
        "exceptions": d["exceptions"],
    }

    timestamp = datetime.now(timezone.utc).isoformat()

    if output_format in ("text", "all"):
        result["text"] = d["template_text"]
    if output_format in ("html", "all"):
        result["html"] = d["template_html"].replace("{system_name}", system_name).replace("{timestamp}", timestamp)
    if output_format in ("code", "all"):
        result["code"] = d["template_code_python"]

    return result


def format_disclosure_text(disclosures: dict) -> str:
    """Format disclosures as human-readable output."""
    lines = ["# Article 50 — Transparency Disclosures", ""]

    items = disclosures.items() if isinstance(disclosures, dict) and "type" not in disclosures else [(disclosures.get("type", "?"), disclosures)]

    for dtype, d in items:
        if "error" in d:
            lines.append(f"Error: {d['error']}")
            continue

        lines.append(f"## {d.get('article', 'Article 50')} — {dtype.replace('_', ' ').title()}")
        lines.append("")
        lines.append(f"Requirement: {d.get('requirement', '')}")
        lines.append(f"Placement: {d.get('placement', '')}")
        lines.append(f"Exceptions: {d.get('exceptions', 'None')}")
        lines.append("")

        if "text" in d:
            lines.append("### Disclosure Text (copy-paste ready)")
            lines.append("")
            lines.append(f"  {d['text']}")
            lines.append("")

        if "html" in d:
            lines.append("### HTML Template")
            lines.append("")
            lines.append(f"  {d['html']}")
            lines.append("")

        if "code" in d:
            lines.append("### Python Code Scaffold")
            lines.append("")
            for code_line in d["code"].split("\n"):
                lines.append(f"  {code_line}")
            lines.append("")

        lines.append("---")
        lines.append("")

    return "\n".join(lines)
