#!/usr/bin/env python3
# regula-ignore — Article 50 disclosure generator carries chatbot and deepfake vocabulary as template copy
"""
Regula Transparency Disclosure Generator (Article 50)

Generates EU AI Act transparency notices for:
- Article 50(1): Chatbots and AI interaction disclosure
- Article 50(2): Synthetic content labelling (text, image, audio, video)
- Article 50(3): Emotion recognition system disclosure
- Article 50(4): Deep fake labelling

Output is an implementation starting point for review, not a compliance-ready
control. Runtime timing, context, accessibility and statutory exceptions cannot
be established by a generated string.
"""
import sys
from datetime import datetime, timezone
from html import escape as html_escape
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))

from omnibus import LIMITED_PROSE, ORIGINAL_PROSE  # noqa: E402


# ---------------------------------------------------------------------------
# Disclosure templates per Article 50 subsection
# ---------------------------------------------------------------------------

DISCLOSURES = {
    "chatbot": {
        "article": "Article 50(1)",
        "requirement": "Providers must design and develop directly interactive AI systems so the natural persons concerned are informed that they are interacting with an AI system, subject to the exceptions in Article 50(1).",
        "template_text": (
            "You are interacting with an AI system. This system is powered by "
            "artificial intelligence and is not a human."
        ),
        "template_html": (
            '<aside class="ai-disclosure" role="note" '
            'aria-labelledby="ai-disclosure-title">'
            '<p id="ai-disclosure-title"><strong>AI system:</strong> You are '
            'interacting with an AI system, not a human.</p></aside>'
        ),
        "template_code_python": (
            "# Article 50(1) — AI interaction disclosure\n"
            "AI_DISCLOSURE = (\n"
            '    "You are interacting with an AI system. "\n'
            '    "This system is powered by artificial intelligence "\n'
            '    "and is not a human."\n'
            ")\n\n"
            "def get_ai_disclosure() -> str:\n"
            '    """Return the AI interaction disclosure notice (Article 50(1))."""\n'
            "    return AI_DISCLOSURE\n"
        ),
        "placement": "Present clearly and accessibly no later than the first interaction. Machine-readable metadata alone is not a perceivable Article 50(1) notice.",
        "exceptions": "Article 50(1) includes an obviousness exception and an exception for systems authorised by law for criminal-offence detection, prevention, investigation or prosecution; the latter does not remove the duty for systems available to the public to report a criminal offence.",
        "limitations": "This sample does not establish obviousness, timing, accessibility in the surrounding interface, territorial scope, provider role, or either statutory exception.",
    },
    "synthetic_text": {
        "article": "Article 50(2)",
        "requirement": "Providers of AI systems generating synthetic audio, image, video or text must mark outputs in a machine-readable format and make them detectable as artificially generated or manipulated, using effective, interoperable, robust and reliable technical solutions as far as technically feasible.",
        "template_text": (
            "This content was generated by an AI system and may not reflect "
            "human authorship. AI-generated content should be independently "
            "verified before reliance."
        ),
        "template_html": (
            '<div class="ai-generated-content" data-ai-generated="true" '
            'data-regula-template="illustrative-not-standard" '
            'data-generator="{system_name}" data-timestamp="{timestamp}">'
            '<p class="ai-label">AI-generated content</p></div>'
        ),
        "template_code_python": (
            "# Article 50(2) — Synthetic content labelling\n"
            "def label_ai_content(content: str, system_name: str) -> dict:\n"
            '    """Label AI-generated content per Article 50(2)."""\n'
            "    return {\n"
            '        "content": content,\n'
            '        "metadata": {\n'
            '            "ai_generated": True,\n'
            '            "generator": system_name,\n'
            '            "timestamp": datetime.now(timezone.utc).isoformat(),\n'
            '            "eu_ai_act_article": "50(2)",\n'
            "        }\n"
            "    }\n"
        ),
        "placement": "Implement a supported output-level marking and detection technique. This proprietary HTML attribute is illustrative metadata, not an interoperability standard or proof of Article 50(2) compliance.",
        "exceptions": "Article 50(2) excludes standard editing assistance that does not substantially alter input data or its semantics, and systems authorised by law for criminal-offence detection, prevention, investigation or prosecution.",
        "limitations": (
            "This sample does not establish machine-readable interoperability, "
            "robustness, reliability, detectability after distribution, technical "
            "feasibility, or the Article 111(4) transition ending "
            f"{LIMITED_PROSE} for systems placed on the market before "
            f"{ORIGINAL_PROSE}."
        ),
    },
    "emotion_recognition": {
        "article": "Article 50(3)",
        "requirement": "Deployers of emotion recognition systems or biometric categorisation systems shall inform natural persons exposed thereto of the operation of the system.",
        "template_text": (
            "This system uses emotion recognition technology to analyse "
            "facial expressions, voice patterns, or other biometric signals. "
            "Your emotional state may be inferred during this interaction."
        ),
        "template_html": (
            '<div class="emotion-recognition-notice" role="alert">'
            '<p><strong>Emotion Recognition Notice:</strong> This system analyses '
            'biometric signals to infer emotional states.</p></div>'
        ),
        "template_code_python": (
            "# Article 50(3) — Emotion recognition disclosure\n"
            "EMOTION_NOTICE = (\n"
            '    "This system uses emotion recognition technology to analyse "\n'
            '    "facial expressions, voice patterns, or other biometric signals. "\n'
            '    "Your emotional state may be inferred during this interaction."\n'
            ")\n"
        ),
        "placement": "Inform exposed natural persons clearly and accessibly no later than their first exposure to the operating system.",
        "exceptions": "Article 50(3) excludes systems authorised by law to detect, prevent or investigate criminal offences. Medical or safety use is not an Article 50(3) exception.",
        "limitations": "This sample does not establish that the system meets the legal definition, that persons see the notice before or at first exposure, accessibility in context, data-protection lawfulness, or the criminal-law exception.",
    },
    "deepfake": {
        "article": "Article 50(4)",
        "requirement": "Deployers of AI systems that generate or manipulate image, audio, or video content constituting a deep fake shall disclose that the content has been artificially generated or manipulated.",
        "template_text": (
            "This content has been artificially generated or manipulated "
            "using AI technology. It does not depict real events."
        ),
        "template_html": (
            '<div class="deepfake-label" role="alert" data-synthetic="true">'
            '<p><strong>AI-Generated Content:</strong> This media has been '
            'artificially generated or manipulated using AI technology.</p></div>'
        ),
        "template_code_python": (
            "# Article 50(4) — Deep fake labelling\n"
            "def label_deepfake(media_path: str, media_type: str) -> dict:\n"
            '    """Label deep fake content per Article 50(4)."""\n'
            "    return {\n"
            '        "media": media_path,\n'
            '        "type": media_type,  # "image", "audio", "video"\n'
            '        "synthetic": True,\n'
            '        "label": "This content has been artificially generated "\n'
            '                 "or manipulated using AI technology.",\n'
            '        "eu_ai_act_article": "50(4)",\n'
            "    }\n"
        ),
        "placement": "Disclose clearly, distinguishably and accessibly no later than first exposure to the deep-fake content.",
        "exceptions": "Article 50(4) includes a criminal-law exception. Evidently artistic, creative, satirical, fictional or analogous content is not exempt: disclosure is still required, but may be made appropriately without hampering display or enjoyment.",
        "limitations": "This sample does not establish that the content meets the deep-fake definition, first-exposure timing, accessibility in context, the appropriate manner for artistic works, or the criminal-law exception.",
    },
}


RUNTIME_REVIEW = (
    {
        "review_id": "article50_5_first_interaction_or_exposure",
        "status": "not_verified",
        "question": "Is the information presented no later than the first interaction or exposure?",
    },
    {
        "review_id": "article50_5_clear_and_distinguishable",
        "status": "not_verified",
        "question": "Is the information clear and distinguishable in the complete interface or publication context?",
    },
    {
        "review_id": "article50_5_accessibility",
        "status": "not_verified",
        "question": "Does the complete implementation meet applicable accessibility requirements?",
    },
    {
        "review_id": "control_failure_state",
        "status": "not_verified",
        "question": "If the disclosure or marking cannot be delivered, is the failure visible and does the affected action fail safely?",
    },
)


# ---------------------------------------------------------------------------
# Generator functions
# ---------------------------------------------------------------------------

def generate_disclosure(
    disclosure_type: str,
    output_format: str = "text",
    system_name: str = "AI System",
) -> dict:
    """Generate a transparency disclosure for a given type.

    Args:
        disclosure_type: One of "chatbot", "synthetic_text", "emotion_recognition", "deepfake", "all"
        output_format: "text", "html", "code", or "all"
        system_name: Name of the AI system for templates.

    Returns:
        Dict with article, requirement, and generated templates.
    """
    if disclosure_type == "all":
        return {
            dtype: generate_disclosure(dtype, output_format, system_name)
            for dtype in DISCLOSURES
        }

    if disclosure_type not in DISCLOSURES:
        return {"error": f"Unknown type: {disclosure_type}. Options: {', '.join(DISCLOSURES.keys())}, all"}

    d = DISCLOSURES[disclosure_type]
    result = {
        "type": disclosure_type,
        "article": d["article"],
        "requirement": d["requirement"],
        "placement": d["placement"],
        "exceptions": d["exceptions"],
        "limitations": d["limitations"],
        "runtime_review": [dict(item) for item in RUNTIME_REVIEW],
    }

    timestamp = datetime.now(timezone.utc).isoformat()

    if output_format in ("text", "all"):
        result["text"] = d["template_text"]
    if output_format in ("html", "all"):
        # Escape user-supplied name before it lands in an HTML template
        # (attribute + text contexts) — a name containing quotes or angle
        # brackets must not break out of the generated snippet.
        safe_name = html_escape(system_name, quote=True)
        result["html"] = d["template_html"].replace("{system_name}", safe_name).replace("{timestamp}", timestamp)
    if output_format in ("code", "all"):
        result["code"] = d["template_code_python"]

    return result


def format_disclosure_text(disclosures: dict) -> str:
    """Format disclosures as human-readable output."""
    lines = ["# Article 50 — Transparency Disclosures", ""]

    # A raw top-level error dict ({"error": ...} with no per-type structure,
    # e.g. the "Unknown type" return of generate_disclosure) must not be
    # iterated as if its keys were disclosure types.
    if isinstance(disclosures, dict) and "error" in disclosures and "type" not in disclosures:
        lines.append(f"Error: {disclosures['error']}")
        return "\n".join(lines)

    items = disclosures.items() if isinstance(disclosures, dict) and "type" not in disclosures else [(disclosures.get("type", "?"), disclosures)]

    for dtype, d in items:
        if not isinstance(d, dict):
            lines.append(f"{dtype}: {d}")
            continue
        if "error" in d:
            lines.append(f"Error: {d['error']}")
            continue

        lines.append(f"## {d.get('article', 'Article 50')} — {dtype.replace('_', ' ').title()}")
        lines.append("")
        lines.append(f"Requirement: {d.get('requirement', '')}")
        lines.append(f"Placement: {d.get('placement', '')}")
        lines.append(f"Exceptions: {d.get('exceptions', 'None')}")
        lines.append(f"Limitations: {d.get('limitations', '')}")
        lines.append("Runtime review: not verified by this generator")
        for item in d.get("runtime_review", []):
            lines.append(
                f"  - {item['review_id']} [{item['status']}]: {item['question']}"
            )
        lines.append("")

        if "text" in d:
            lines.append("### Illustrative disclosure text")
            lines.append("")
            lines.append(f"  {d['text']}")
            lines.append("")

        if "html" in d:
            lines.append("### HTML Template")
            lines.append("")
            lines.append(f"  {d['html']}")
            lines.append("")

        if "code" in d:
            lines.append("### Python Code Scaffold")
            lines.append("")
            for code_line in d["code"].split("\n"):
                lines.append(f"  {code_line}")
            lines.append("")

        lines.append("---")
        lines.append("")

    return "\n".join(lines)
